name: MudbaseSDK
targets:
  MudbaseSDK:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [MudbaseSDK]
    info:
      path: ./Info.plist
      version: 1.2.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
