//
// AuthenticationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AuthenticationAPI {

    /**
     Accept organization invitation
     
     - parameter acceptInviteRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func acceptInvite(acceptInviteRequest: AcceptInviteRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: AcceptInvite201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return acceptInviteWithRequestBuilder(acceptInviteRequest: acceptInviteRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Accept organization invitation
     - POST /api/auth/accept-invite
     - Accept an organization invitation using the token from the invite email link (e.g. `/invite/{token}?orgId=...`). Creates a new user with the invited email and adds them to the organization with the invited role. Returns a JWT and user so the client can log the user in immediately. No authentication required. 
     - parameter acceptInviteRequest: (body)  
     - returns: RequestBuilder<AcceptInvite201Response> 
     */
    open class func acceptInviteWithRequestBuilder(acceptInviteRequest: AcceptInviteRequest) -> RequestBuilder<AcceptInvite201Response> {
        let localVariablePath = "/api/auth/accept-invite"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: acceptInviteRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AcceptInvite201Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Confirm password reset with OTP (project-based)
     
     - parameter confirmLocalPasswordResetWithOtpRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func confirmLocalPasswordResetWithOtp(confirmLocalPasswordResetWithOtpRequest: ConfirmLocalPasswordResetWithOtpRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return confirmLocalPasswordResetWithOtpWithRequestBuilder(confirmLocalPasswordResetWithOtpRequest: confirmLocalPasswordResetWithOtpRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Confirm password reset with OTP (project-based)
     - POST /api/auth/local/password-reset/confirm
     - Set new password using the OTP sent to the user's email. Call after POST /api/auth/local/password-reset with projectId. Rate limited (OTP limit). If the user's email was not yet verified, it is marked as verified upon successful reset. 
     - parameter confirmLocalPasswordResetWithOtpRequest: (body)  
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func confirmLocalPasswordResetWithOtpWithRequestBuilder(confirmLocalPasswordResetWithOtpRequest: ConfirmLocalPasswordResetWithOtpRequest) -> RequestBuilder<MessageResponse> {
        let localVariablePath = "/api/auth/local/password-reset/confirm"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: confirmLocalPasswordResetWithOtpRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Convert anonymous account to full account
     
     - parameter convertAnonymousAccountRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func convertAnonymousAccount(convertAnonymousAccountRequest: ConvertAnonymousAccountRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: ConvertAnonymousAccount200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return convertAnonymousAccountWithRequestBuilder(convertAnonymousAccountRequest: convertAnonymousAccountRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Convert anonymous account to full account
     - POST /api/auth/anonymous/convert
     - Convert an anonymous user session to a full authenticated account. Preserves user data. Requires JWT Bearer token authentication. Both OrgBearerAuth and ProjectBearerAuth are supported (they use the same JWT token format). API keys are not supported for this endpoint. 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter convertAnonymousAccountRequest: (body)  
     - returns: RequestBuilder<ConvertAnonymousAccount200Response> 
     */
    open class func convertAnonymousAccountWithRequestBuilder(convertAnonymousAccountRequest: ConvertAnonymousAccountRequest) -> RequestBuilder<ConvertAnonymousAccount200Response> {
        let localVariablePath = "/api/auth/anonymous/convert"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: convertAnonymousAccountRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ConvertAnonymousAccount200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create anonymous session
     
     - parameter createAnonymousSessionRequest: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createAnonymousSession(createAnonymousSessionRequest: CreateAnonymousSessionRequest? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: CreateAnonymousSession200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return createAnonymousSessionWithRequestBuilder(createAnonymousSessionRequest: createAnonymousSessionRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create anonymous session
     - POST /api/auth/anonymous
     - Create an anonymous user session for guest access. Users can later convert to full accounts.
     - parameter createAnonymousSessionRequest: (body)  (optional)
     - returns: RequestBuilder<CreateAnonymousSession200Response> 
     */
    open class func createAnonymousSessionWithRequestBuilder(createAnonymousSessionRequest: CreateAnonymousSessionRequest? = nil) -> RequestBuilder<CreateAnonymousSession200Response> {
        let localVariablePath = "/api/auth/anonymous"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createAnonymousSessionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateAnonymousSession200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get all available OAuth providers
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getAvailableOAuthProviders(apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetAvailableOAuthProviders200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getAvailableOAuthProvidersWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get all available OAuth providers
     - GET /api/auth/oauth/providers/available
     - Returns a list of all supported OAuth providers with their configuration details
     - returns: RequestBuilder<GetAvailableOAuthProviders200Response> 
     */
    open class func getAvailableOAuthProvidersWithRequestBuilder() -> RequestBuilder<GetAvailableOAuthProviders200Response> {
        let localVariablePath = "/api/auth/oauth/providers/available"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetAvailableOAuthProviders200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get current session
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getCurrentSession(apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: SessionResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getCurrentSessionWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get current session
     - GET /api/auth/session
     - Get the current authenticated user session information. Requires JWT Bearer token authentication. Both OrgBearerAuth and ProjectBearerAuth are supported (they use the same JWT token format). API keys are not supported for this endpoint. 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - returns: RequestBuilder<SessionResponse> 
     */
    open class func getCurrentSessionWithRequestBuilder() -> RequestBuilder<SessionResponse> {
        let localVariablePath = "/api/auth/session"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SessionResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get current session (project-based)
     
     - parameter projectId: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getLocalSession(projectId: String? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetLocalSession200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getLocalSessionWithRequestBuilder(projectId: projectId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get current session (project-based)
     - GET /api/auth/local/session
     - Get the current authenticated user session (project-based). Requires JWT Bearer token authentication. Both OrgBearerAuth and ProjectBearerAuth are supported (they use the same JWT token format). API keys are not supported for this endpoint. 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (query)  (optional)
     - returns: RequestBuilder<GetLocalSession200Response> 
     */
    open class func getLocalSessionWithRequestBuilder(projectId: String? = nil) -> RequestBuilder<GetLocalSession200Response> {
        let localVariablePath = "/api/auth/local/session"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "projectId": (wrappedValue: projectId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetLocalSession200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get available OAuth providers for organization-based auth
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getOrgOAuthProviders(apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetOrgOAuthProviders200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getOrgOAuthProvidersWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get available OAuth providers for organization-based auth
     - GET /api/auth/oauth-org/providers
     - Returns a list of OAuth providers that are configured and available for organization-based authentication. Providers are configured via environment variables (e.g., GOOGLE_CLIENT_ID, GITHUB_CLIENT_ID). 
     - returns: RequestBuilder<GetOrgOAuthProviders200Response> 
     */
    open class func getOrgOAuthProvidersWithRequestBuilder() -> RequestBuilder<GetOrgOAuthProviders200Response> {
        let localVariablePath = "/api/auth/oauth-org/providers"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetOrgOAuthProviders200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter provider
     */
    public enum Provider_initiateOAuth: String, CaseIterable {
        case google = "google"
        case github = "github"
        case facebook = "facebook"
        case microsoft = "microsoft"
        case apple = "apple"
        case twitter = "twitter"
        case discord = "discord"
        case linkedin = "linkedin"
        case dropbox = "dropbox"
        case slack = "slack"
        case reddit = "reddit"
        case twitch = "twitch"
        case figma = "figma"
        case zoom = "zoom"
        case bitbucket = "bitbucket"
        case salesforce = "salesforce"
        case shopify = "shopify"
        case line = "line"
        case spotify = "spotify"
        case strava = "strava"
        case paypal = "paypal"
        case asana = "asana"
        case trello = "trello"
        case okta = "okta"
        case gitea = "gitea"
        case yandex = "yandex"
        case yahoo = "yahoo"
        case vk = "vk"
        case meetup = "meetup"
    }

    /**
     Initiate OAuth authentication
     
     - parameter provider: (path)  
     - parameter projectId: (path)  
     - parameter redirectUrl: (query) The URL to redirect to after authentication. Must be pre-registered in project settings. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func initiateOAuth(provider: Provider_initiateOAuth, projectId: String, redirectUrl: String? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return initiateOAuthWithRequestBuilder(provider: provider, projectId: projectId, redirectUrl: redirectUrl).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Initiate OAuth authentication
     - GET /api/auth/oauth/{provider}/{projectId}
     - Initiates OAuth authentication flow for a specified provider and project. The OAuth provider must be configured and enabled for the project first. Returns an HTTP 302 redirect to the OAuth provider's consent screen. Note: Swagger \"Try it out\" may show \"Failed to fetch\" for this endpoint due to browser CORS restrictions on cross-origin redirects. Use top-level browser navigation or curl to test. 
     - parameter provider: (path)  
     - parameter projectId: (path)  
     - parameter redirectUrl: (query) The URL to redirect to after authentication. Must be pre-registered in project settings. (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func initiateOAuthWithRequestBuilder(provider: Provider_initiateOAuth, projectId: String, redirectUrl: String? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/api/auth/oauth/{provider}/{projectId}"
        let providerPreEscape = "\(provider.rawValue)"
        let providerPostEscape = providerPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{provider}", with: providerPostEscape, options: .literal, range: nil)
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "redirect_url": (wrappedValue: redirectUrl?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MudbaseSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter provider
     */
    public enum Provider_initiateOrgOAuth: String, CaseIterable {
        case google = "google"
        case github = "github"
        case facebook = "facebook"
        case microsoft = "microsoft"
        case discord = "discord"
        case linkedin = "linkedin"
    }

    /**
     Initiate OAuth authentication for organization
     
     - parameter provider: (path)  
     - parameter redirectUrl: (query) The URL to redirect to after authentication (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func initiateOrgOAuth(provider: Provider_initiateOrgOAuth, redirectUrl: String? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return initiateOrgOAuthWithRequestBuilder(provider: provider, redirectUrl: redirectUrl).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Initiate OAuth authentication for organization
     - GET /api/auth/oauth-org/{provider}
     - Initiates OAuth authentication flow for organization-level signup/login. The OAuth provider must be configured via environment variables (e.g., GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET). After successful authentication, creates a new organization and user account, or logs in existing user. 
     - parameter provider: (path)  
     - parameter redirectUrl: (query) The URL to redirect to after authentication (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func initiateOrgOAuthWithRequestBuilder(provider: Provider_initiateOrgOAuth, redirectUrl: String? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/api/auth/oauth-org/{provider}"
        let providerPreEscape = "\(provider.rawValue)"
        let providerPostEscape = providerPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{provider}", with: providerPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "redirect_url": (wrappedValue: redirectUrl?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MudbaseSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Login user (project-based)
     
     - parameter loginLocalUserRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func loginLocalUser(loginLocalUserRequest: LoginLocalUserRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: LoginLocalUser200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return loginLocalUserWithRequestBuilder(loginLocalUserRequest: loginLocalUserRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Login user (project-based)
     - POST /api/auth/local/login
     - When the project has **requireEmailVerification** enabled and the user has not verified their email, returns 403 with code **EMAIL_VERIFICATION_REQUIRED** (user must verify email first, then login again). 
     - parameter loginLocalUserRequest: (body)  
     - returns: RequestBuilder<LoginLocalUser200Response> 
     */
    open class func loginLocalUserWithRequestBuilder(loginLocalUserRequest: LoginLocalUserRequest) -> RequestBuilder<LoginLocalUser200Response> {
        let localVariablePath = "/api/auth/local/login"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: loginLocalUserRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LoginLocalUser200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Login user
     
     - parameter loginRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func loginUser(loginRequest: LoginRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: AuthResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return loginUserWithRequestBuilder(loginRequest: loginRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Login user
     - POST /api/auth/login
     - parameter loginRequest: (body)  
     - returns: RequestBuilder<AuthResponse> 
     */
    open class func loginUserWithRequestBuilder(loginRequest: LoginRequest) -> RequestBuilder<AuthResponse> {
        let localVariablePath = "/api/auth/login"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: loginRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AuthResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Logout user (project-based)
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func logoutLocalUser(apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return logoutLocalUserWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Logout user (project-based)
     - POST /api/auth/local/logout
     - Logout the current authenticated user session (project-based). Requires JWT Bearer token authentication. Both OrgBearerAuth and ProjectBearerAuth are supported (they use the same JWT token format). API keys are not supported for this endpoint. 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func logoutLocalUserWithRequestBuilder() -> RequestBuilder<MessageResponse> {
        let localVariablePath = "/api/auth/local/logout"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Logout user
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func logoutUser(apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return logoutUserWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Logout user
     - POST /api/auth/logout
     - Logout the current authenticated user session. Requires JWT Bearer token authentication. Both OrgBearerAuth and ProjectBearerAuth are supported (they use the same JWT token format). API keys are not supported for this endpoint. 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func logoutUserWithRequestBuilder() -> RequestBuilder<MessageResponse> {
        let localVariablePath = "/api/auth/logout"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     OAuth callback handler (project-based)
     
     - parameter provider: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func oauthCallback(provider: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return oauthCallbackWithRequestBuilder(provider: provider).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     OAuth callback handler (project-based)
     - GET /api/auth/oauth/callback/{provider}
     - Handles OAuth callback for project-based authentication. This route must be matched before /api/auth/oauth/{provider}/{projectId}. Redirects to frontend with query params token, refreshToken, and expiresIn. 
     - parameter provider: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func oauthCallbackWithRequestBuilder(provider: String) -> RequestBuilder<Void> {
        var localVariablePath = "/api/auth/oauth/callback/{provider}"
        let providerPreEscape = "\(APIHelper.mapValueToPathItem(provider))"
        let providerPostEscape = providerPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{provider}", with: providerPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MudbaseSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter provider
     */
    public enum Provider_orgOAuthCallback: String, CaseIterable {
        case google = "google"
        case github = "github"
        case facebook = "facebook"
        case microsoft = "microsoft"
        case discord = "discord"
        case linkedin = "linkedin"
    }

    /**
     OAuth callback handler for organization
     
     - parameter provider: (path)  
     - parameter code: (query) Authorization code from OAuth provider (optional)
     - parameter state: (query) State parameter for CSRF protection (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func orgOAuthCallback(provider: Provider_orgOAuthCallback, code: String? = nil, state: String? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return orgOAuthCallbackWithRequestBuilder(provider: provider, code: code, state: state).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     OAuth callback handler for organization
     - GET /api/auth/oauth-org/callback/{provider}
     - Handles OAuth callback for organization-based authentication. Creates a new organization and user account if the user doesn't exist, or logs in existing user. Redirects to frontend with query params token, refreshToken, and expiresIn. 
     - parameter provider: (path)  
     - parameter code: (query) Authorization code from OAuth provider (optional)
     - parameter state: (query) State parameter for CSRF protection (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func orgOAuthCallbackWithRequestBuilder(provider: Provider_orgOAuthCallback, code: String? = nil, state: String? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/api/auth/oauth-org/callback/{provider}"
        let providerPreEscape = "\(provider.rawValue)"
        let providerPostEscape = providerPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{provider}", with: providerPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "code": (wrappedValue: code?.encodeToJSON(), isExplode: true),
            "state": (wrappedValue: state?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MudbaseSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Refresh access token (org and project)
     
     - parameter refreshTokenRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func refreshToken(refreshTokenRequest: RefreshTokenRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: RefreshToken200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return refreshTokenWithRequestBuilder(refreshTokenRequest: refreshTokenRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Refresh access token (org and project)
     - POST /api/auth/refresh
     - Exchange a valid refresh token for a new JWT access token and refresh token. Works for both **org-based** (platform/dashboard) and **project-based** auth; the same endpoint is used. The previous refresh token is invalidated (rotation). If the same refresh token is used again, the session is revoked (reuse detection). 
     - parameter refreshTokenRequest: (body)  
     - returns: RequestBuilder<RefreshToken200Response> 
     */
    open class func refreshTokenWithRequestBuilder(refreshTokenRequest: RefreshTokenRequest) -> RequestBuilder<RefreshToken200Response> {
        let localVariablePath = "/api/auth/refresh"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: refreshTokenRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RefreshToken200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Register new user (project-based)
     
     - parameter registerLocalUserRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func registerLocalUser(registerLocalUserRequest: RegisterLocalUserRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: RegisterLocalUser201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return registerLocalUserWithRequestBuilder(registerLocalUserRequest: registerLocalUserRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Register new user (project-based)
     - POST /api/auth/local/register
     - When the project has **requireEmailVerification** enabled (default), the response is 201 with **requireVerification: true** and **no token**; the user must verify their email then sign in via login. When email verification is disabled, a token and refreshToken are returned. 
     - parameter registerLocalUserRequest: (body)  
     - returns: RequestBuilder<RegisterLocalUser201Response> 
     */
    open class func registerLocalUserWithRequestBuilder(registerLocalUserRequest: RegisterLocalUserRequest) -> RequestBuilder<RegisterLocalUser201Response> {
        let localVariablePath = "/api/auth/local/register"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: registerLocalUserRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RegisterLocalUser201Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Register new user
     
     - parameter registerRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func registerUser(registerRequest: RegisterRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: AuthResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return registerUserWithRequestBuilder(registerRequest: registerRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Register new user
     - POST /api/auth/register
     - parameter registerRequest: (body)  
     - returns: RequestBuilder<AuthResponse> 
     */
    open class func registerUserWithRequestBuilder(registerRequest: RegisterRequest) -> RequestBuilder<AuthResponse> {
        let localVariablePath = "/api/auth/register"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: registerRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AuthResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Request password reset (project-based, OTP)
     
     - parameter requestLocalPasswordResetRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func requestLocalPasswordReset(requestLocalPasswordResetRequest: RequestLocalPasswordResetRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return requestLocalPasswordResetWithRequestBuilder(requestLocalPasswordResetRequest: requestLocalPasswordResetRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Request password reset (project-based, OTP)
     - POST /api/auth/local/password-reset
     - When projectId is provided, sends a 6-digit OTP to the user's email (project-based reset uses OTP, not link). When projectId is omitted, sends a token link (org/platform local account). Rate limited. 
     - parameter requestLocalPasswordResetRequest: (body)  
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func requestLocalPasswordResetWithRequestBuilder(requestLocalPasswordResetRequest: RequestLocalPasswordResetRequest) -> RequestBuilder<MessageResponse> {
        let localVariablePath = "/api/auth/local/password-reset"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestLocalPasswordResetRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Request password reset (organization / platform)
     
     - parameter requestPasswordResetRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func requestPasswordReset(requestPasswordResetRequest: RequestPasswordResetRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return requestPasswordResetWithRequestBuilder(requestPasswordResetRequest: requestPasswordResetRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Request password reset (organization / platform)
     - POST /api/auth/password-reset
     - Sends a password reset link to the user's email. Use this for organization (platform) accounts. For project-based accounts use POST /api/auth/local/password-reset with projectId (sends OTP instead). 
     - parameter requestPasswordResetRequest: (body)  
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func requestPasswordResetWithRequestBuilder(requestPasswordResetRequest: RequestPasswordResetRequest) -> RequestBuilder<MessageResponse> {
        let localVariablePath = "/api/auth/password-reset"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestPasswordResetRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Resend verification email (no auth)
     
     - parameter resendVerificationAuthRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func resendVerificationAuth(resendVerificationAuthRequest: ResendVerificationAuthRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return resendVerificationAuthWithRequestBuilder(resendVerificationAuthRequest: resendVerificationAuthRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Resend verification email (no auth)
     - POST /api/auth/resend-verification
     - Sends a new verification email to the given email (and optional project). For unauthenticated users who have not verified yet. Rate limited (e.g. 3 per 15 min per IP). 
     - parameter resendVerificationAuthRequest: (body)  
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func resendVerificationAuthWithRequestBuilder(resendVerificationAuthRequest: ResendVerificationAuthRequest) -> RequestBuilder<MessageResponse> {
        let localVariablePath = "/api/auth/resend-verification"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: resendVerificationAuthRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Reset password with token (project-based, legacy)
     
     - parameter token: (path)  
     - parameter resetLocalPasswordRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func resetLocalPassword(token: String, resetLocalPasswordRequest: ResetLocalPasswordRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return resetLocalPasswordWithRequestBuilder(token: token, resetLocalPasswordRequest: resetLocalPasswordRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Reset password with token (project-based, legacy)
     - POST /api/auth/local/password-reset/{token}
     - Legacy token-based completion. Prefer OTP flow: use POST .../password-reset/confirm with the OTP sent to email for project-based resets. 
     - parameter token: (path)  
     - parameter resetLocalPasswordRequest: (body)  
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func resetLocalPasswordWithRequestBuilder(token: String, resetLocalPasswordRequest: ResetLocalPasswordRequest) -> RequestBuilder<MessageResponse> {
        var localVariablePath = "/api/auth/local/password-reset/{token}"
        let tokenPreEscape = "\(APIHelper.mapValueToPathItem(token))"
        let tokenPostEscape = tokenPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{token}", with: tokenPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: resetLocalPasswordRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Reset password with token (organization / platform)
     
     - parameter token: (path)  
     - parameter resetPasswordRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func resetPassword(token: String, resetPasswordRequest: ResetPasswordRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return resetPasswordWithRequestBuilder(token: token, resetPasswordRequest: resetPasswordRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Reset password with token (organization / platform)
     - POST /api/auth/password-reset/{token}
     - Set new password using the token from the reset link. Validate the token first with POST /api/auth/password-reset/validate before showing the form. If the user's email was not yet verified, it is marked as verified upon successful reset. 
     - parameter token: (path)  
     - parameter resetPasswordRequest: (body)  
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func resetPasswordWithRequestBuilder(token: String, resetPasswordRequest: ResetPasswordRequest) -> RequestBuilder<MessageResponse> {
        var localVariablePath = "/api/auth/password-reset/{token}"
        let tokenPreEscape = "\(APIHelper.mapValueToPathItem(token))"
        let tokenPostEscape = tokenPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{token}", with: tokenPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: resetPasswordRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Send magic link
     
     - parameter magicLinkRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func sendMagicLink(magicLinkRequest: MagicLinkRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return sendMagicLinkWithRequestBuilder(magicLinkRequest: magicLinkRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Send magic link
     - POST /api/auth/magic-link/send
     - parameter magicLinkRequest: (body)  
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func sendMagicLinkWithRequestBuilder(magicLinkRequest: MagicLinkRequest) -> RequestBuilder<MessageResponse> {
        let localVariablePath = "/api/auth/magic-link/send"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: magicLinkRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Send OTP code
     
     - parameter oTPSendRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func sendOTP(oTPSendRequest: OTPSendRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return sendOTPWithRequestBuilder(oTPSendRequest: oTPSendRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Send OTP code
     - POST /api/auth/otp/send
     - parameter oTPSendRequest: (body)  
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func sendOTPWithRequestBuilder(oTPSendRequest: OTPSendRequest) -> RequestBuilder<MessageResponse> {
        let localVariablePath = "/api/auth/otp/send"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: oTPSendRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Validate password reset token
     
     - parameter validatePasswordResetTokenRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func validatePasswordResetToken(validatePasswordResetTokenRequest: ValidatePasswordResetTokenRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: ValidatePasswordResetToken200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return validatePasswordResetTokenWithRequestBuilder(validatePasswordResetTokenRequest: validatePasswordResetTokenRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Validate password reset token
     - POST /api/auth/password-reset/validate
     - Call before showing the \"set new password\" form. Validates that the token from the reset link is still valid and not expired. Organization (platform) reset only. 
     - parameter validatePasswordResetTokenRequest: (body)  
     - returns: RequestBuilder<ValidatePasswordResetToken200Response> 
     */
    open class func validatePasswordResetTokenWithRequestBuilder(validatePasswordResetTokenRequest: ValidatePasswordResetTokenRequest) -> RequestBuilder<ValidatePasswordResetToken200Response> {
        let localVariablePath = "/api/auth/password-reset/validate"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: validatePasswordResetTokenRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ValidatePasswordResetToken200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Verify email address (no auth)
     
     - parameter verifyEmailAuthRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func verifyEmailAuth(verifyEmailAuthRequest: VerifyEmailAuthRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return verifyEmailAuthWithRequestBuilder(verifyEmailAuthRequest: verifyEmailAuthRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Verify email address (no auth)
     - POST /api/auth/verify-email
     - Verifies the user's email using the token from the link sent at signup. Use this for both organization and project signups (unauthenticated). Same behavior as POST /api/users/verify-email. 
     - parameter verifyEmailAuthRequest: (body)  
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func verifyEmailAuthWithRequestBuilder(verifyEmailAuthRequest: VerifyEmailAuthRequest) -> RequestBuilder<MessageResponse> {
        let localVariablePath = "/api/auth/verify-email"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: verifyEmailAuthRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Verify magic link
     
     - parameter verifyMagicLinkRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func verifyMagicLink(verifyMagicLinkRequest: VerifyMagicLinkRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: AuthResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return verifyMagicLinkWithRequestBuilder(verifyMagicLinkRequest: verifyMagicLinkRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Verify magic link
     - POST /api/auth/magic-link/verify
     - parameter verifyMagicLinkRequest: (body)  
     - returns: RequestBuilder<AuthResponse> 
     */
    open class func verifyMagicLinkWithRequestBuilder(verifyMagicLinkRequest: VerifyMagicLinkRequest) -> RequestBuilder<AuthResponse> {
        let localVariablePath = "/api/auth/magic-link/verify"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: verifyMagicLinkRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AuthResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Verify OTP code
     
     - parameter oTPVerifyRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func verifyOTP(oTPVerifyRequest: OTPVerifyRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: AuthResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return verifyOTPWithRequestBuilder(oTPVerifyRequest: oTPVerifyRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Verify OTP code
     - POST /api/auth/otp/verify
     - parameter oTPVerifyRequest: (body)  
     - returns: RequestBuilder<AuthResponse> 
     */
    open class func verifyOTPWithRequestBuilder(oTPVerifyRequest: OTPVerifyRequest) -> RequestBuilder<AuthResponse> {
        let localVariablePath = "/api/auth/otp/verify"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: oTPVerifyRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AuthResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
