//
// BackupsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class BackupsAPI {

    /**
     Create project backup
     
     - parameter projectId: (path)  
     - parameter createBackupRequest: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createBackup(projectId: String, createBackupRequest: CreateBackupRequest? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: CreateBackup201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return createBackupWithRequestBuilder(projectId: projectId, createBackupRequest: createBackupRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create project backup
     - POST /api/projects/{projectId}/backups
     - Create a backup of project data, optionally including files and wallets. Supports both JWT Bearer token and API key authentication.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter createBackupRequest: (body)  (optional)
     - returns: RequestBuilder<CreateBackup201Response> 
     */
    open class func createBackupWithRequestBuilder(projectId: String, createBackupRequest: CreateBackupRequest? = nil) -> RequestBuilder<CreateBackup201Response> {
        var localVariablePath = "/api/projects/{projectId}/backups"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createBackupRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateBackup201Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete backup
     
     - parameter projectId: (path)  
     - parameter backupId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteBackup(projectId: String, backupId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: DeleteBackup200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteBackupWithRequestBuilder(projectId: projectId, backupId: backupId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete backup
     - DELETE /api/projects/{projectId}/backups/{backupId}
     - Delete a project backup. Supports both JWT Bearer token and API key authentication.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter backupId: (path)  
     - returns: RequestBuilder<DeleteBackup200Response> 
     */
    open class func deleteBackupWithRequestBuilder(projectId: String, backupId: String) -> RequestBuilder<DeleteBackup200Response> {
        var localVariablePath = "/api/projects/{projectId}/backups/{backupId}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let backupIdPreEscape = "\(APIHelper.mapValueToPathItem(backupId))"
        let backupIdPostEscape = backupIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{backupId}", with: backupIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteBackup200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List project backups
     
     - parameter projectId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listBackups(projectId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: ListBackups200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return listBackupsWithRequestBuilder(projectId: projectId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List project backups
     - GET /api/projects/{projectId}/backups
     - Get all backups for a project. Supports both JWT Bearer token and API key authentication.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - returns: RequestBuilder<ListBackups200Response> 
     */
    open class func listBackupsWithRequestBuilder(projectId: String) -> RequestBuilder<ListBackups200Response> {
        var localVariablePath = "/api/projects/{projectId}/backups"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListBackups200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Restore from backup
     
     - parameter projectId: (path)  
     - parameter backupId: (path)  
     - parameter restoreBackupRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func restoreBackup(projectId: String, backupId: String, restoreBackupRequest: RestoreBackupRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: RestoreBackup200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return restoreBackupWithRequestBuilder(projectId: projectId, backupId: backupId, restoreBackupRequest: restoreBackupRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Restore from backup
     - POST /api/projects/{projectId}/backups/{backupId}/restore
     - Restore project data from a backup. Supports replace or merge modes. Supports both JWT Bearer token and API key authentication.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter backupId: (path)  
     - parameter restoreBackupRequest: (body)  
     - returns: RequestBuilder<RestoreBackup200Response> 
     */
    open class func restoreBackupWithRequestBuilder(projectId: String, backupId: String, restoreBackupRequest: RestoreBackupRequest) -> RequestBuilder<RestoreBackup200Response> {
        var localVariablePath = "/api/projects/{projectId}/backups/{backupId}/restore"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let backupIdPreEscape = "\(APIHelper.mapValueToPathItem(backupId))"
        let backupIdPostEscape = backupIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{backupId}", with: backupIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: restoreBackupRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RestoreBackup200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
