//
// BillingAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class BillingAPI {

    /**
     Cancel subscription
     
     - parameter subscriptionId: (path)  
     - parameter cancelSubscriptionRequest: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func cancelSubscription(subscriptionId: String, cancelSubscriptionRequest: CancelSubscriptionRequest? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: DeleteRole200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return cancelSubscriptionWithRequestBuilder(subscriptionId: subscriptionId, cancelSubscriptionRequest: cancelSubscriptionRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Cancel subscription
     - POST /api/billing/subscriptions/{subscriptionId}/cancel
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter subscriptionId: (path)  
     - parameter cancelSubscriptionRequest: (body)  (optional)
     - returns: RequestBuilder<DeleteRole200Response> 
     */
    open class func cancelSubscriptionWithRequestBuilder(subscriptionId: String, cancelSubscriptionRequest: CancelSubscriptionRequest? = nil) -> RequestBuilder<DeleteRole200Response> {
        var localVariablePath = "/api/billing/subscriptions/{subscriptionId}/cancel"
        let subscriptionIdPreEscape = "\(APIHelper.mapValueToPathItem(subscriptionId))"
        let subscriptionIdPostEscape = subscriptionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{subscriptionId}", with: subscriptionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: cancelSubscriptionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteRole200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Check feature access (public)
     
     - parameter projectId: (path)  
     - parameter email: (query) Customer email 
     - parameter feature: (query) Feature slug to check access for 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func checkFeatureAccess(projectId: String, email: String, feature: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: CheckFeatureAccess200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return checkFeatureAccessWithRequestBuilder(projectId: projectId, email: email, feature: feature).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Check feature access (public)
     - GET /api/billing/public/projects/{projectId}/feature-access
     - parameter projectId: (path)  
     - parameter email: (query) Customer email 
     - parameter feature: (query) Feature slug to check access for 
     - returns: RequestBuilder<CheckFeatureAccess200Response> 
     */
    open class func checkFeatureAccessWithRequestBuilder(projectId: String, email: String, feature: String) -> RequestBuilder<CheckFeatureAccess200Response> {
        var localVariablePath = "/api/billing/public/projects/{projectId}/feature-access"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "email": (wrappedValue: email.encodeToJSON(), isExplode: true),
            "feature": (wrappedValue: feature.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CheckFeatureAccess200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Check subscription status (public)
     
     - parameter projectId: (path)  
     - parameter email: (query) Customer email to check subscription for 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func checkSubscription(projectId: String, email: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: CheckSubscription200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return checkSubscriptionWithRequestBuilder(projectId: projectId, email: email).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Check subscription status (public)
     - GET /api/billing/public/projects/{projectId}/subscription
     - parameter projectId: (path)  
     - parameter email: (query) Customer email to check subscription for 
     - returns: RequestBuilder<CheckSubscription200Response> 
     */
    open class func checkSubscriptionWithRequestBuilder(projectId: String, email: String) -> RequestBuilder<CheckSubscription200Response> {
        var localVariablePath = "/api/billing/public/projects/{projectId}/subscription"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "email": (wrappedValue: email.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CheckSubscription200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Create checkout session (fiat)
     
     - parameter projectId: (path) Project ID 
     - parameter createCheckoutSessionRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createCheckoutSession(projectId: String, createCheckoutSessionRequest: CreateCheckoutSessionRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: CreateCheckoutSession200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return createCheckoutSessionWithRequestBuilder(projectId: projectId, createCheckoutSessionRequest: createCheckoutSessionRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create checkout session (fiat)
     - POST /api/billing/public/projects/{projectId}/checkout
     - **Customer subscription flow — Step 2.** Creates a fiat checkout session. Request body must include planId (from GET public plans), billingCycle (monthly|yearly), and customerInfo.email. Redirect the user to **checkoutUrl** (same URL as authorizationUrl). After payment, call verify-payment with **reference** (mudbase_...). Response includes only fiat fields (no paymentAddress, paymentOptions, network, asset, or pmt_ references). 
     - parameter projectId: (path) Project ID 
     - parameter createCheckoutSessionRequest: (body)  
     - returns: RequestBuilder<CreateCheckoutSession200Response> 
     */
    open class func createCheckoutSessionWithRequestBuilder(projectId: String, createCheckoutSessionRequest: CreateCheckoutSessionRequest) -> RequestBuilder<CreateCheckoutSession200Response> {
        var localVariablePath = "/api/billing/public/projects/{projectId}/checkout"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createCheckoutSessionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateCheckoutSession200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Create billing plan
     
     - parameter projectId: (path)  
     - parameter createPlanRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createPlan(projectId: String, createPlanRequest: CreatePlanRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: CreatePlan201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return createPlanWithRequestBuilder(projectId: projectId, createPlanRequest: createPlanRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create billing plan
     - POST /api/billing/projects/{projectId}/plans
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter createPlanRequest: (body)  
     - returns: RequestBuilder<CreatePlan201Response> 
     */
    open class func createPlanWithRequestBuilder(projectId: String, createPlanRequest: CreatePlanRequest) -> RequestBuilder<CreatePlan201Response> {
        var localVariablePath = "/api/billing/projects/{projectId}/plans"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createPlanRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreatePlan201Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete billing plan
     
     - parameter projectId: (path)  
     - parameter planId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deletePlan(projectId: String, planId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return deletePlanWithRequestBuilder(projectId: projectId, planId: planId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete billing plan
     - DELETE /api/billing/projects/{projectId}/plans/{planId}
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter planId: (path)  
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func deletePlanWithRequestBuilder(projectId: String, planId: String) -> RequestBuilder<MessageResponse> {
        var localVariablePath = "/api/billing/projects/{projectId}/plans/{planId}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let planIdPreEscape = "\(APIHelper.mapValueToPathItem(planId))"
        let planIdPostEscape = planIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{planId}", with: planIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Download invoice PDF
     
     - parameter projectId: (path)  
     - parameter invoiceId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func downloadInvoice(projectId: String, invoiceId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: URL?, _ error: Error?) -> Void)) -> RequestTask {
        return downloadInvoiceWithRequestBuilder(projectId: projectId, invoiceId: invoiceId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Download invoice PDF
     - GET /api/billing/projects/{projectId}/invoices/{invoiceId}/download
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter invoiceId: (path)  
     - returns: RequestBuilder<URL> 
     */
    open class func downloadInvoiceWithRequestBuilder(projectId: String, invoiceId: String) -> RequestBuilder<URL> {
        var localVariablePath = "/api/billing/projects/{projectId}/invoices/{invoiceId}/download"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let invoiceIdPreEscape = "\(APIHelper.mapValueToPathItem(invoiceId))"
        let invoiceIdPostEscape = invoiceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{invoiceId}", with: invoiceIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Enable payment processing for organization
     
     - parameter orgId: (path)  
     - parameter enablePaymentProcessingRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func enablePaymentProcessing(orgId: String, enablePaymentProcessingRequest: EnablePaymentProcessingRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: EnablePaymentProcessing200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return enablePaymentProcessingWithRequestBuilder(orgId: orgId, enablePaymentProcessingRequest: enablePaymentProcessingRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Enable payment processing for organization
     - POST /api/orgs/{orgId}/payment-processing/enable
     - Creates a payment-collection subaccount for the org with the provided bank details. Use USD-capable bank (e.g. country US) for USD settlement. BVN only required when country is NG. Requires owner or admin role.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - parameter orgId: (path)  
     - parameter enablePaymentProcessingRequest: (body)  
     - returns: RequestBuilder<EnablePaymentProcessing200Response> 
     */
    open class func enablePaymentProcessingWithRequestBuilder(orgId: String, enablePaymentProcessingRequest: EnablePaymentProcessingRequest) -> RequestBuilder<EnablePaymentProcessing200Response> {
        var localVariablePath = "/api/orgs/{orgId}/payment-processing/enable"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: enablePaymentProcessingRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EnablePaymentProcessing200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Export invoice (e.g. PDF URL or file)
     
     - parameter projectId: (path)  
     - parameter invoiceId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func exportInvoice(projectId: String, invoiceId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: DownloadInvoice200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return exportInvoiceWithRequestBuilder(projectId: projectId, invoiceId: invoiceId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Export invoice (e.g. PDF URL or file)
     - GET /api/billing/projects/{projectId}/invoices/{invoiceId}/export
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter invoiceId: (path)  
     - returns: RequestBuilder<DownloadInvoice200Response> 
     */
    open class func exportInvoiceWithRequestBuilder(projectId: String, invoiceId: String) -> RequestBuilder<DownloadInvoice200Response> {
        var localVariablePath = "/api/billing/projects/{projectId}/invoices/{invoiceId}/export"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let invoiceIdPreEscape = "\(APIHelper.mapValueToPathItem(invoiceId))"
        let invoiceIdPostEscape = invoiceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{invoiceId}", with: invoiceIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DownloadInvoice200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get billing estimate and forecast
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getBillingEstimate(apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetBillingEstimate200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getBillingEstimateWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get billing estimate and forecast
     - GET /api/billing/estimate
     - Returns current-month overage estimate and an optional end-of-month forecast for the authenticated organization. Includes spend limit settings (soft/hard) and whether usage is currently blocked. Requires org-level JWT. 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - returns: RequestBuilder<GetBillingEstimate200Response> 
     */
    open class func getBillingEstimateWithRequestBuilder() -> RequestBuilder<GetBillingEstimate200Response> {
        let localVariablePath = "/api/billing/estimate"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetBillingEstimate200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get checkout payment details (not used for fiat billing)
     
     - parameter projectId: (path)  
     - parameter paymentId: (path) Opaque id from checkout (fiat billing does not expose pollable payment state here) 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getCheckoutPayment(projectId: String, paymentId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return getCheckoutPaymentWithRequestBuilder(projectId: projectId, paymentId: paymentId).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get checkout payment details (not used for fiat billing)
     - GET /api/billing/public/projects/{projectId}/checkout/{paymentId}
     - **Fiat-only billing:** checkout is completed on the payment gateway's hosted page; there is no server-side payment intent to poll. The live API returns **404** for this route. Reserved for compatibility; do not rely on a success body for project billing. 
     - parameter projectId: (path)  
     - parameter paymentId: (path) Opaque id from checkout (fiat billing does not expose pollable payment state here) 
     - returns: RequestBuilder<Void> 
     */
    open class func getCheckoutPaymentWithRequestBuilder(projectId: String, paymentId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/api/billing/public/projects/{projectId}/checkout/{paymentId}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let paymentIdPreEscape = "\(APIHelper.mapValueToPathItem(paymentId))"
        let paymentIdPostEscape = paymentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{paymentId}", with: paymentIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MudbaseSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get billing dashboard data
     
     - parameter projectId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getDashboard(projectId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetDashboard200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getDashboardWithRequestBuilder(projectId: projectId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get billing dashboard data
     - GET /api/billing/projects/{projectId}/dashboard
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - returns: RequestBuilder<GetDashboard200Response> 
     */
    open class func getDashboardWithRequestBuilder(projectId: String) -> RequestBuilder<GetDashboard200Response> {
        var localVariablePath = "/api/billing/projects/{projectId}/dashboard"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetDashboard200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get fee breakdown for a given amount
     
     - parameter orgId: (path)  
     - parameter amount: (query)  
     - parameter currency: (query)  (optional, default to "USD")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getFeeBreakdown(orgId: String, amount: Double, currency: String? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetFeeBreakdown200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getFeeBreakdownWithRequestBuilder(orgId: orgId, amount: amount, currency: currency).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get fee breakdown for a given amount
     - GET /api/orgs/{orgId}/payment-processing/fee-breakdown
     - Returns orgReceives, platformPercent, platformFixed, processingFee for the given amount (7% + $0.50 platform fee; processing fee absorbed from platform share).
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - parameter orgId: (path)  
     - parameter amount: (query)  
     - parameter currency: (query)  (optional, default to "USD")
     - returns: RequestBuilder<GetFeeBreakdown200Response> 
     */
    open class func getFeeBreakdownWithRequestBuilder(orgId: String, amount: Double, currency: String? = nil) -> RequestBuilder<GetFeeBreakdown200Response> {
        var localVariablePath = "/api/orgs/{orgId}/payment-processing/fee-breakdown"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "amount": (wrappedValue: amount.encodeToJSON(), isExplode: true),
            "currency": (wrappedValue: currency?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetFeeBreakdown200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get single invoice
     
     - parameter projectId: (path)  
     - parameter invoiceId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getInvoice(projectId: String, invoiceId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetInvoice200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getInvoiceWithRequestBuilder(projectId: projectId, invoiceId: invoiceId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get single invoice
     - GET /api/billing/projects/{projectId}/invoices/{invoiceId}
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter invoiceId: (path)  
     - returns: RequestBuilder<GetInvoice200Response> 
     */
    open class func getInvoiceWithRequestBuilder(projectId: String, invoiceId: String) -> RequestBuilder<GetInvoice200Response> {
        var localVariablePath = "/api/billing/projects/{projectId}/invoices/{invoiceId}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let invoiceIdPreEscape = "\(APIHelper.mapValueToPathItem(invoiceId))"
        let invoiceIdPostEscape = invoiceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{invoiceId}", with: invoiceIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetInvoice200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List project invoices
     
     - parameter projectId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getInvoices(projectId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetInvoices200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getInvoicesWithRequestBuilder(projectId: projectId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List project invoices
     - GET /api/billing/projects/{projectId}/invoices
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - returns: RequestBuilder<GetInvoices200Response> 
     */
    open class func getInvoicesWithRequestBuilder(projectId: String) -> RequestBuilder<GetInvoices200Response> {
        var localVariablePath = "/api/billing/projects/{projectId}/invoices"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetInvoices200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter status
     */
    public enum Status_getPaymentRecords: String, CaseIterable {
        case pending = "pending"
        case successful = "successful"
        case failed = "failed"
    }

    /**
     List fiat payment records for organization
     
     - parameter orgId: (path)  
     - parameter page: (query)  (optional, default to 1)
     - parameter limit: (query)  (optional, default to 20)
     - parameter status: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPaymentRecords(orgId: String, page: Int? = nil, limit: Int? = nil, status: Status_getPaymentRecords? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetPaymentRecords200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getPaymentRecordsWithRequestBuilder(orgId: orgId, page: page, limit: limit, status: status).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List fiat payment records for organization
     - GET /api/orgs/{orgId}/payment-processing/records
     - Paginated list of FiatPaymentRecord for this org (txRef, amount, orgReceives, status, paidAt).
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - parameter orgId: (path)  
     - parameter page: (query)  (optional, default to 1)
     - parameter limit: (query)  (optional, default to 20)
     - parameter status: (query)  (optional)
     - returns: RequestBuilder<GetPaymentRecords200Response> 
     */
    open class func getPaymentRecordsWithRequestBuilder(orgId: String, page: Int? = nil, limit: Int? = nil, status: Status_getPaymentRecords? = nil) -> RequestBuilder<GetPaymentRecords200Response> {
        var localVariablePath = "/api/orgs/{orgId}/payment-processing/records"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetPaymentRecords200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get billing plans
     
     - parameter projectId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPlans(projectId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetPlans200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getPlansWithRequestBuilder(projectId: projectId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get billing plans
     - GET /api/billing/projects/{projectId}/plans
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - returns: RequestBuilder<GetPlans200Response> 
     */
    open class func getPlansWithRequestBuilder(projectId: String) -> RequestBuilder<GetPlans200Response> {
        var localVariablePath = "/api/billing/projects/{projectId}/plans"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetPlans200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get public plans (no auth required)
     
     - parameter projectId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPublicPlans(projectId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetPublicPlans200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getPublicPlansWithRequestBuilder(projectId: projectId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get public plans (no auth required)
     - GET /api/billing/public/projects/{projectId}/plans
     - **Customer subscription flow — Step 1.** Returns all active plans for the project. Use a plan's _id as planId in the checkout request. No authentication required (for pricing/checkout pages). 
     - parameter projectId: (path)  
     - returns: RequestBuilder<GetPublicPlans200Response> 
     */
    open class func getPublicPlansWithRequestBuilder(projectId: String) -> RequestBuilder<GetPublicPlans200Response> {
        var localVariablePath = "/api/billing/public/projects/{projectId}/plans"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetPublicPlans200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get one subscription tier by id
     
     - parameter planId: (path) Plan id (free, starter, growth, scale, enterprise) 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getSubscriptionTierById(planId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetSubscriptionTierById200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getSubscriptionTierByIdWithRequestBuilder(planId: planId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get one subscription tier by id
     - GET /api/billing/plans/{planId}
     - Returns a single org-level BaaS plan (free, starter, growth, scale, enterprise). Public; no auth required.
     - parameter planId: (path) Plan id (free, starter, growth, scale, enterprise) 
     - returns: RequestBuilder<GetSubscriptionTierById200Response> 
     */
    open class func getSubscriptionTierByIdWithRequestBuilder(planId: String) -> RequestBuilder<GetSubscriptionTierById200Response> {
        var localVariablePath = "/api/billing/plans/{planId}"
        let planIdPreEscape = "\(APIHelper.mapValueToPathItem(planId))"
        let planIdPostEscape = planIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{planId}", with: planIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetSubscriptionTierById200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get subscription tiers (org-level BaaS plans)
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getSubscriptionTiers(apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetSubscriptionTiers200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getSubscriptionTiersWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get subscription tiers (org-level BaaS plans)
     - GET /api/billing/plans
     - **Org-level BaaS plan catalog** (source of truth in paymentService.js). Returns Free, Starter ($29), Growth ($69), Scale ($199), Enterprise. Use for pricing page and to get plan ids for POST /api/billing/org/checkout. Public; no auth required. Each plan includes id (free|starter|growth|scale|enterprise), name, description, price (cents), priceYearly (cents, 8% off), currency, limits, overages, enforcement. 
     - returns: RequestBuilder<GetSubscriptionTiers200Response> 
     */
    open class func getSubscriptionTiersWithRequestBuilder() -> RequestBuilder<GetSubscriptionTiers200Response> {
        let localVariablePath = "/api/billing/plans"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetSubscriptionTiers200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get subscriptions
     
     - parameter projectId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getSubscriptions(projectId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetSubscriptions200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getSubscriptionsWithRequestBuilder(projectId: projectId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get subscriptions
     - GET /api/billing/projects/{projectId}/subscriptions
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - returns: RequestBuilder<GetSubscriptions200Response> 
     */
    open class func getSubscriptionsWithRequestBuilder(projectId: String) -> RequestBuilder<GetSubscriptions200Response> {
        var localVariablePath = "/api/billing/projects/{projectId}/subscriptions"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetSubscriptions200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Payment gateway webhook
     
     - parameter handleFlutterwaveWebhookRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func handleFlutterwaveWebhook(handleFlutterwaveWebhookRequest: HandleFlutterwaveWebhookRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: HandleFlutterwaveWebhook200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return handleFlutterwaveWebhookWithRequestBuilder(handleFlutterwaveWebhookRequest: handleFlutterwaveWebhookRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Payment gateway webhook
     - POST /api/billing/webhooks/flutterwave
     - Receives payment gateway webhook events (charge.completed, payment.successful). No auth; verified by verif-hash header. - Subscription billing: meta without isPaymentProcessing triggers verifyPaymentAndCreateSubscription (mudbase_xxx refs). - Payment processing: meta.isPaymentProcessing === true triggers fiat payment record (mudbase_fiat_xxx refs); org share goes to org subaccount, platform fee to main or configured subaccounts. 
     - parameter handleFlutterwaveWebhookRequest: (body)  
     - returns: RequestBuilder<HandleFlutterwaveWebhook200Response> 
     */
    open class func handleFlutterwaveWebhookWithRequestBuilder(handleFlutterwaveWebhookRequest: HandleFlutterwaveWebhookRequest) -> RequestBuilder<HandleFlutterwaveWebhook200Response> {
        let localVariablePath = "/api/billing/webhooks/flutterwave"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: handleFlutterwaveWebhookRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<HandleFlutterwaveWebhook200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Initialize org-level BaaS plan payment (Starter, Growth, Scale)
     
     - parameter initializeOrgPlanCheckoutRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func initializeOrgPlanCheckout(initializeOrgPlanCheckoutRequest: InitializeOrgPlanCheckoutRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: InitializeOrgPlanCheckout200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return initializeOrgPlanCheckoutWithRequestBuilder(initializeOrgPlanCheckoutRequest: initializeOrgPlanCheckoutRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Initialize org-level BaaS plan payment (Starter, Growth, Scale)
     - POST /api/billing/org/checkout
     - **Org plan payment flow — Step 2.** Creates a payment link for the authenticated org to subscribe to a BaaS plan (starter, growth, scale). Enterprise has no price; use contact-sales flow. Redirect the user to the returned link; after payment, call POST /api/billing/org/verify-payment with the tx_ref from the redirect. Requires org-level JWT. 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - parameter initializeOrgPlanCheckoutRequest: (body)  
     - returns: RequestBuilder<InitializeOrgPlanCheckout200Response> 
     */
    open class func initializeOrgPlanCheckoutWithRequestBuilder(initializeOrgPlanCheckoutRequest: InitializeOrgPlanCheckoutRequest) -> RequestBuilder<InitializeOrgPlanCheckout200Response> {
        let localVariablePath = "/api/billing/org/checkout"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: initializeOrgPlanCheckoutRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InitializeOrgPlanCheckout200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Initialize fiat payment with split (org subaccount + platform fee)
     
     - parameter orgId: (path)  
     - parameter initializePaymentRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func initializePayment(orgId: String, initializePaymentRequest: InitializePaymentRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: InitializePayment200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return initializePaymentWithRequestBuilder(orgId: orgId, initializePaymentRequest: initializePaymentRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Initialize fiat payment with split (org subaccount + platform fee)
     - POST /api/orgs/{orgId}/payment-processing/initialize-payment
     - Creates a payment link. Customer pays; org receives (amount - 7% - $0.50) to their subaccount; platform fee (7% + $0.50, minus processing fee) stays on main account or goes to configured platform subaccounts. Requires payment processing enabled for org.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - parameter orgId: (path)  
     - parameter initializePaymentRequest: (body)  
     - returns: RequestBuilder<InitializePayment200Response> 
     */
    open class func initializePaymentWithRequestBuilder(orgId: String, initializePaymentRequest: InitializePaymentRequest) -> RequestBuilder<InitializePayment200Response> {
        var localVariablePath = "/api/orgs/{orgId}/payment-processing/initialize-payment"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: initializePaymentRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InitializePayment200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Initialize fiat payment (project-scoped)
     
     - parameter projectId: (path)  
     - parameter initializePaymentForProjectRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func initializePaymentForProject(projectId: String, initializePaymentForProjectRequest: InitializePaymentForProjectRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return initializePaymentForProjectWithRequestBuilder(projectId: projectId, initializePaymentForProjectRequest: initializePaymentForProjectRequest).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Initialize fiat payment (project-scoped)
     - POST /api/projects/{projectId}/payment-processing/initialize-payment
     - Same as org-level initialize-payment; projectId from path is used for scope and tx_ref. Resolves project to org and uses org's payment-processing subaccount.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter initializePaymentForProjectRequest: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func initializePaymentForProjectWithRequestBuilder(projectId: String, initializePaymentForProjectRequest: InitializePaymentForProjectRequest) -> RequestBuilder<Void> {
        var localVariablePath = "/api/projects/{projectId}/payment-processing/initialize-payment"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: initializePaymentForProjectRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MudbaseSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Record usage (public)
     
     - parameter projectId: (path)  
     - parameter recordUsageRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func recordUsage(projectId: String, recordUsageRequest: RecordUsageRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MessageResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return recordUsageWithRequestBuilder(projectId: projectId, recordUsageRequest: recordUsageRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Record usage (public)
     - POST /api/billing/public/projects/{projectId}/usage
     - parameter projectId: (path)  
     - parameter recordUsageRequest: (body)  
     - returns: RequestBuilder<MessageResponse> 
     */
    open class func recordUsageWithRequestBuilder(projectId: String, recordUsageRequest: RecordUsageRequest) -> RequestBuilder<MessageResponse> {
        var localVariablePath = "/api/billing/public/projects/{projectId}/usage"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: recordUsageRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MessageResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Update billing plan
     
     - parameter projectId: (path)  
     - parameter planId: (path)  
     - parameter updatePlanRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updatePlan(projectId: String, planId: String, updatePlanRequest: UpdatePlanRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: CreatePlan201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return updatePlanWithRequestBuilder(projectId: projectId, planId: planId, updatePlanRequest: updatePlanRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update billing plan
     - PATCH /api/billing/projects/{projectId}/plans/{planId}
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter planId: (path)  
     - parameter updatePlanRequest: (body)  
     - returns: RequestBuilder<CreatePlan201Response> 
     */
    open class func updatePlanWithRequestBuilder(projectId: String, planId: String, updatePlanRequest: UpdatePlanRequest) -> RequestBuilder<CreatePlan201Response> {
        var localVariablePath = "/api/billing/projects/{projectId}/plans/{planId}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let planIdPreEscape = "\(APIHelper.mapValueToPathItem(planId))"
        let planIdPostEscape = planIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{planId}", with: planIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updatePlanRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreatePlan201Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Verify org-level plan payment
     
     - parameter txRef: (query) Payment reference (mudbase_org_...) from checkout redirect (optional)
     - parameter reference: (query) Alias for tx_ref (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func verifyOrgPlanPayment(txRef: String? = nil, reference: String? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: VerifyOrgPlanPayment200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return verifyOrgPlanPaymentWithRequestBuilder(txRef: txRef, reference: reference).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Verify org-level plan payment
     - POST /api/billing/org/verify-payment
     - **Org plan payment flow — Step 3.** Call after the user completes payment (redirect or webhook). Pass tx_ref (or reference) from the payment redirect. Updates org plan and billing; idempotent. No auth required (redirect callback can call this). 
     - parameter txRef: (query) Payment reference (mudbase_org_...) from checkout redirect (optional)
     - parameter reference: (query) Alias for tx_ref (optional)
     - returns: RequestBuilder<VerifyOrgPlanPayment200Response> 
     */
    open class func verifyOrgPlanPaymentWithRequestBuilder(txRef: String? = nil, reference: String? = nil) -> RequestBuilder<VerifyOrgPlanPayment200Response> {
        let localVariablePath = "/api/billing/org/verify-payment"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "tx_ref": (wrappedValue: txRef?.encodeToJSON(), isExplode: true),
            "reference": (wrappedValue: reference?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VerifyOrgPlanPayment200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Verify payment and create subscription
     
     - parameter projectId: (path)  
     - parameter reference: (query) Payment transaction reference (mudbase_...) 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func verifyPayment(projectId: String, reference: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: VerifyPayment200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return verifyPaymentWithRequestBuilder(projectId: projectId, reference: reference).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Verify payment and create subscription
     - POST /api/billing/public/projects/{projectId}/verify-payment
     - **Customer subscription flow — Step 3.** Call after the user completes payment. Pass **reference** as query (?reference=mudbase_...). On success, a subscription is created. No auth required when using the platform gateway (mudbase_ refs). Org-level gateway verification may require JWT. References starting with pmt_ are rejected (crypto billing is not enabled on this API). 
     - parameter projectId: (path)  
     - parameter reference: (query) Payment transaction reference (mudbase_...) 
     - returns: RequestBuilder<VerifyPayment200Response> 
     */
    open class func verifyPaymentWithRequestBuilder(projectId: String, reference: String) -> RequestBuilder<VerifyPayment200Response> {
        var localVariablePath = "/api/billing/public/projects/{projectId}/verify-payment"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "reference": (wrappedValue: reference.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VerifyPayment200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
