//
// KYCAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class KYCAPI {

    /**
     List recent compliance webhook deliveries
     
     - parameter limit: (query) Maximum number of events to return. (optional, default to 25)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiKycEventsGet(limit: Int? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return apiKycEventsGetWithRequestBuilder(limit: limit).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List recent compliance webhook deliveries
     - GET /api/kyc/events
     - Audit trail of compliance webhook events received for this organization and whether Mudbase forwarded each one to the organization's own endpoint. Owner, admin, and developer roles.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - parameter limit: (query) Maximum number of events to return. (optional, default to 25)
     - returns: RequestBuilder<Void> 
     */
    open class func apiKycEventsGetWithRequestBuilder(limit: Int? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/api/kyc/events"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MudbaseSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Start a platform KYC session
     
     - parameter apiKycSessionsPostRequest: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiKycSessionsPost(apiKycSessionsPostRequest: ApiKycSessionsPostRequest? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return apiKycSessionsPostWithRequestBuilder(apiKycSessionsPostRequest: apiKycSessionsPostRequest).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Start a platform KYC session
     - POST /api/kyc/sessions
     - Creates a verification session for the caller's organization. Owner/admin only.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - parameter apiKycSessionsPostRequest: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func apiKycSessionsPostWithRequestBuilder(apiKycSessionsPostRequest: ApiKycSessionsPostRequest? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/api/kyc/sessions"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: apiKycSessionsPostRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MudbaseSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get the organization's platform KYC status
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiKycStatusGet(apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return apiKycStatusGetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get the organization's platform KYC status
     - GET /api/kyc/status
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - returns: RequestBuilder<Void> 
     */
    open class func apiKycStatusGetWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/api/kyc/status"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MudbaseSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get a single KYC verification record
     
     - parameter id: (path) Verification record id. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiKycVerificationsIdGet(id: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return apiKycVerificationsIdGetWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get a single KYC verification record
     - GET /api/kyc/verifications/{id}
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - parameter id: (path) Verification record id. 
     - returns: RequestBuilder<Void> 
     */
    open class func apiKycVerificationsIdGetWithRequestBuilder(id: String) -> RequestBuilder<Void> {
        var localVariablePath = "/api/kyc/verifications/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MudbaseSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get white-label KYC webhook config
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiKycWebhookConfigGet(apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: ApiKycWebhookConfigGet200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return apiKycWebhookConfigGetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get white-label KYC webhook config
     - GET /api/kyc/webhook-config
     - Returns the destination URL where the organization's own system receives KYC results and whether a signing secret is set. The secret value itself is never returned. Owner/admin only.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - returns: RequestBuilder<ApiKycWebhookConfigGet200Response> 
     */
    open class func apiKycWebhookConfigGetWithRequestBuilder() -> RequestBuilder<ApiKycWebhookConfigGet200Response> {
        let localVariablePath = "/api/kyc/webhook-config"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiKycWebhookConfigGet200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Set white-label KYC webhook config
     
     - parameter apiKycWebhookConfigPutRequest: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiKycWebhookConfigPut(apiKycWebhookConfigPutRequest: ApiKycWebhookConfigPutRequest? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: ApiKycWebhookConfigPut200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return apiKycWebhookConfigPutWithRequestBuilder(apiKycWebhookConfigPutRequest: apiKycWebhookConfigPutRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Set white-label KYC webhook config
     - PUT /api/kyc/webhook-config
     - Updates the destination URL and/or signing secret used to deliver KYC results to the organization's own system. The outbound URL is SSRF-validated. When generateSecret is true a new secret is created and returned once. Owner/admin only.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - parameter apiKycWebhookConfigPutRequest: (body)  (optional)
     - returns: RequestBuilder<ApiKycWebhookConfigPut200Response> 
     */
    open class func apiKycWebhookConfigPutWithRequestBuilder(apiKycWebhookConfigPutRequest: ApiKycWebhookConfigPutRequest? = nil) -> RequestBuilder<ApiKycWebhookConfigPut200Response> {
        let localVariablePath = "/api/kyc/webhook-config"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: apiKycWebhookConfigPutRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiKycWebhookConfigPut200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send a signed test event to the configured webhook endpoint
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiKycWebhookConfigTestPost(apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: ApiKycWebhookConfigTestPost200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return apiKycWebhookConfigTestPostWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Send a signed test event to the configured webhook endpoint
     - POST /api/kyc/webhook-config/test
     - Delivers a sample `kyc.test` payload, signed exactly like a real event, so you can confirm your receiver and signature verification work. Ignores your event subscription. Owner/admin only.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - returns: RequestBuilder<ApiKycWebhookConfigTestPost200Response> 
     */
    open class func apiKycWebhookConfigTestPostWithRequestBuilder() -> RequestBuilder<ApiKycWebhookConfigTestPost200Response> {
        let localVariablePath = "/api/kyc/webhook-config/test"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiKycWebhookConfigTestPost200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List available verification workflows
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiKycWorkflowsGet(apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: ApiKycWorkflowsGet200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return apiKycWorkflowsGetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List available verification workflows
     - GET /api/kyc/workflows
     - Returns the verification workflows configured on this Mudbase account, split into kyc (individual identity) and kyb (business verification). Used to choose a default workflow in the console instead of pasting a workflow UUID. Owner/admin only.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - returns: RequestBuilder<ApiKycWorkflowsGet200Response> 
     */
    open class func apiKycWorkflowsGetWithRequestBuilder() -> RequestBuilder<ApiKycWorkflowsGet200Response> {
        let localVariablePath = "/api/kyc/workflows"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiKycWorkflowsGet200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Start a business verification (KYB) session for one of your business customers
     
     - parameter projectId: (path)  
     - parameter apiProjectsProjectIdKybSessionsPostRequest: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiProjectsProjectIdKybSessionsPost(projectId: String, apiProjectsProjectIdKybSessionsPostRequest: ApiProjectsProjectIdKybSessionsPostRequest? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return apiProjectsProjectIdKybSessionsPostWithRequestBuilder(projectId: projectId, apiProjectsProjectIdKybSessionsPostRequest: apiProjectsProjectIdKybSessionsPostRequest).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Start a business verification (KYB) session for one of your business customers
     - POST /api/projects/{projectId}/kyb/sessions
     - Creates a KYB session scoped to your project. The workflow is resolved from the request, then the organization's configured default KYB workflow, then the platform default. Results arrive at your configured KYC webhook as `kyb.completed`.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - parameter projectId: (path)  
     - parameter apiProjectsProjectIdKybSessionsPostRequest: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func apiProjectsProjectIdKybSessionsPostWithRequestBuilder(projectId: String, apiProjectsProjectIdKybSessionsPostRequest: ApiProjectsProjectIdKybSessionsPostRequest? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/api/projects/{projectId}/kyb/sessions"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: apiProjectsProjectIdKybSessionsPostRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MudbaseSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
