//
// MultiRoleAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class MultiRoleAPI {

    /**
     * enum for parameter provider
     */
    public enum Provider_authOauthSignupWithRole: String, CaseIterable {
        case google = "google"
        case github = "github"
        case facebook = "facebook"
        case microsoft = "microsoft"
        case apple = "apple"
        case twitter = "twitter"
        case discord = "discord"
        case linkedin = "linkedin"
        case dropbox = "dropbox"
        case slack = "slack"
        case reddit = "reddit"
        case twitch = "twitch"
        case figma = "figma"
        case zoom = "zoom"
        case bitbucket = "bitbucket"
        case salesforce = "salesforce"
        case shopify = "shopify"
        case line = "line"
        case spotify = "spotify"
        case strava = "strava"
        case paypal = "paypal"
        case asana = "asana"
        case trello = "trello"
        case okta = "okta"
        case gitea = "gitea"
        case yandex = "yandex"
        case yahoo = "yahoo"
        case vk = "vk"
        case meetup = "meetup"
    }

    /**
     OAuth signup with specific role
     
     - parameter role: (path) Path segment must match the role&#39;s &#x60;signupEndpoint&#x60; (default &#x60;customer&#x60;; use each role&#39;s configured endpoint). 
     - parameter provider: (path) OAuth provider (e.g. google, github). 
     - parameter projectId: (path) Project ID. 
     - parameter redirectUrl: (query) The URL to redirect to after authentication (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func authOauthSignupWithRole(role: String, provider: Provider_authOauthSignupWithRole, projectId: String, redirectUrl: String? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: UsersLinkOAuthProvider200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return authOauthSignupWithRoleWithRequestBuilder(role: role, provider: provider, projectId: projectId, redirectUrl: redirectUrl).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     OAuth signup with specific role
     - GET /api/auth/oauth/signup/{role}/{provider}/{projectId}
     - Public endpoint that initiates OAuth signup flow with a specific role assigned during registration. The OAuth provider must be configured and enabled for the project first. The role must be available for signup in the project's multi-role configuration. After successful OAuth authentication, the user will be created with the specified role. No authentication required - this is a public signup endpoint. 
     - parameter role: (path) Path segment must match the role&#39;s &#x60;signupEndpoint&#x60; (default &#x60;customer&#x60;; use each role&#39;s configured endpoint). 
     - parameter provider: (path) OAuth provider (e.g. google, github). 
     - parameter projectId: (path) Project ID. 
     - parameter redirectUrl: (query) The URL to redirect to after authentication (optional)
     - returns: RequestBuilder<UsersLinkOAuthProvider200Response> 
     */
    open class func authOauthSignupWithRoleWithRequestBuilder(role: String, provider: Provider_authOauthSignupWithRole, projectId: String, redirectUrl: String? = nil) -> RequestBuilder<UsersLinkOAuthProvider200Response> {
        var localVariablePath = "/api/auth/oauth/signup/{role}/{provider}/{projectId}"
        let rolePreEscape = "\(APIHelper.mapValueToPathItem(role))"
        let rolePostEscape = rolePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{role}", with: rolePostEscape, options: .literal, range: nil)
        let providerPreEscape = "\(provider.rawValue)"
        let providerPostEscape = providerPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{provider}", with: providerPostEscape, options: .literal, range: nil)
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "redirect_url": (wrappedValue: redirectUrl?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UsersLinkOAuthProvider200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Register user with specific role (Local Auth)
     
     - parameter role: (path) Must match the role&#39;s &#x60;signupEndpoint&#x60; (default &#x60;customer&#x60;; other values for roles you add). 
     - parameter authRegisterWithRoleRequest: (body) Registration payload (email, password, firstName, lastName, projectId). 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func authRegisterWithRole(role: String, authRegisterWithRoleRequest: AuthRegisterWithRoleRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return authRegisterWithRoleWithRequestBuilder(role: role, authRegisterWithRoleRequest: authRegisterWithRoleRequest).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Register user with specific role (Local Auth)
     - POST /api/auth/local/signup/{role}
     - Public endpoint for user registration with a specific role. The path segment must match a role's `signupEndpoint` (default starter is `customer`; add more roles via multi-role API). No authentication required - this is a public signup endpoint. 
     - parameter role: (path) Must match the role&#39;s &#x60;signupEndpoint&#x60; (default &#x60;customer&#x60;; other values for roles you add). 
     - parameter authRegisterWithRoleRequest: (body) Registration payload (email, password, firstName, lastName, projectId). 
     - returns: RequestBuilder<Void> 
     */
    open class func authRegisterWithRoleWithRequestBuilder(role: String, authRegisterWithRoleRequest: AuthRegisterWithRoleRequest) -> RequestBuilder<Void> {
        var localVariablePath = "/api/auth/local/signup/{role}"
        let rolePreEscape = "\(APIHelper.mapValueToPathItem(role))"
        let rolePostEscape = rolePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{role}", with: rolePostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: authRegisterWithRoleRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MudbaseSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Add custom role
     
     - parameter projectId: (path) Project ID. 
     - parameter multiRoleAddRoleRequest: (body) Custom role definition. Use &#x60;collectionPermissions&#x60; to apply CRUD per collection slug (e.g. users/products/orders). &#x60;defaultPermissions&#x60; is optional for global/base permissions. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func multiRoleAddRole(projectId: String, multiRoleAddRoleRequest: MultiRoleAddRoleRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MultiRoleToggleRole200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return multiRoleAddRoleWithRequestBuilder(projectId: projectId, multiRoleAddRoleRequest: multiRoleAddRoleRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add custom role
     - POST /api/projects/{projectId}/multi-role/roles
     - Add a custom role to a project with specific permissions and signup endpoint. Optional **featurePermissions** must align with app JWT gates — see schema `AppRoleFeaturePermissions`. Accepts BearerToken (JWT) or ApiKeyAuth (X-API-Key). 
     - Bearer Token:
       - type: http
       - name: BearerToken
     - parameter projectId: (path) Project ID. 
     - parameter multiRoleAddRoleRequest: (body) Custom role definition. Use &#x60;collectionPermissions&#x60; to apply CRUD per collection slug (e.g. users/products/orders). &#x60;defaultPermissions&#x60; is optional for global/base permissions. 
     - returns: RequestBuilder<MultiRoleToggleRole200Response> 
     */
    open class func multiRoleAddRoleWithRequestBuilder(projectId: String, multiRoleAddRoleRequest: MultiRoleAddRoleRequest) -> RequestBuilder<MultiRoleToggleRole200Response> {
        var localVariablePath = "/api/projects/{projectId}/multi-role/roles"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: multiRoleAddRoleRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MultiRoleToggleRole200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Apply Admin / User / Viewer feature permission preset
     
     - parameter projectId: (path) Project ID. 
     - parameter roleSlug: (path) Role slug to apply the preset to (e.g. &#x60;customer&#x60;). 
     - parameter multiRoleApplyRoleFeaturePresetRequest: (body) JSON body with &#x60;preset&#x60; set to &#x60;admin&#x60;, &#x60;user&#x60;, or &#x60;viewer&#x60;. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func multiRoleApplyRoleFeaturePreset(projectId: String, roleSlug: String, multiRoleApplyRoleFeaturePresetRequest: MultiRoleApplyRoleFeaturePresetRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return multiRoleApplyRoleFeaturePresetWithRequestBuilder(projectId: projectId, roleSlug: roleSlug, multiRoleApplyRoleFeaturePresetRequest: multiRoleApplyRoleFeaturePresetRequest).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Apply Admin / User / Viewer feature permission preset
     - POST /api/projects/{projectId}/multi-role/roles/{roleSlug}/apply-preset
     - Sets `featurePermissions` from preset `admin`, `user`, or `viewer`.
     - Bearer Token:
       - type: http
       - name: BearerToken
     - parameter projectId: (path) Project ID. 
     - parameter roleSlug: (path) Role slug to apply the preset to (e.g. &#x60;customer&#x60;). 
     - parameter multiRoleApplyRoleFeaturePresetRequest: (body) JSON body with &#x60;preset&#x60; set to &#x60;admin&#x60;, &#x60;user&#x60;, or &#x60;viewer&#x60;. 
     - returns: RequestBuilder<Void> 
     */
    open class func multiRoleApplyRoleFeaturePresetWithRequestBuilder(projectId: String, roleSlug: String, multiRoleApplyRoleFeaturePresetRequest: MultiRoleApplyRoleFeaturePresetRequest) -> RequestBuilder<Void> {
        var localVariablePath = "/api/projects/{projectId}/multi-role/roles/{roleSlug}/apply-preset"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let roleSlugPreEscape = "\(APIHelper.mapValueToPathItem(roleSlug))"
        let roleSlugPostEscape = roleSlugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{roleSlug}", with: roleSlugPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: multiRoleApplyRoleFeaturePresetRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MudbaseSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get available roles for signup
     
     - parameter projectId: (path) Project ID. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func multiRoleGetAvailableRoles(projectId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MultiRoleGetAvailableRoles200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return multiRoleGetAvailableRolesWithRequestBuilder(projectId: projectId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get available roles for signup
     - GET /api/projects/{projectId}/multi-role/roles/available
     - Get all available roles for user signup in a project. Accepts BearerToken (JWT) or ApiKeyAuth (X-API-Key). 
     - Bearer Token:
       - type: http
       - name: BearerToken
     - parameter projectId: (path) Project ID. 
     - returns: RequestBuilder<MultiRoleGetAvailableRoles200Response> 
     */
    open class func multiRoleGetAvailableRolesWithRequestBuilder(projectId: String) -> RequestBuilder<MultiRoleGetAvailableRoles200Response> {
        var localVariablePath = "/api/projects/{projectId}/multi-role/roles/available"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MultiRoleGetAvailableRoles200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get multi-role feature configuration
     
     - parameter projectId: (path) Project ID. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func multiRoleGetConfig(projectId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MultiRoleGetConfig200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return multiRoleGetConfigWithRequestBuilder(projectId: projectId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get multi-role feature configuration
     - GET /api/projects/{projectId}/multi-role
     - Returns project app roles (default one editable `customer` starter until you add more) and settings.
     - Bearer Token:
       - type: http
       - name: BearerToken
     - parameter projectId: (path) Project ID. 
     - returns: RequestBuilder<MultiRoleGetConfig200Response> 
     */
    open class func multiRoleGetConfigWithRequestBuilder(projectId: String) -> RequestBuilder<MultiRoleGetConfig200Response> {
        var localVariablePath = "/api/projects/{projectId}/multi-role"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MultiRoleGetConfig200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get permissions matrix (collections + featurePermissions)
     
     - parameter projectId: (path) Project ID whose multi-role matrix is returned. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func multiRoleGetPermissionsMatrix(projectId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MultiRoleGetPermissionsMatrix200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return multiRoleGetPermissionsMatrixWithRequestBuilder(projectId: projectId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get permissions matrix (collections + featurePermissions)
     - GET /api/projects/{projectId}/permissions-matrix
     - Per-collection role actions and per-role `featurePermissions` for app-role gates.
     - Bearer Token:
       - type: http
       - name: BearerToken
     - parameter projectId: (path) Project ID whose multi-role matrix is returned. 
     - returns: RequestBuilder<MultiRoleGetPermissionsMatrix200Response> 
     */
    open class func multiRoleGetPermissionsMatrixWithRequestBuilder(projectId: String) -> RequestBuilder<MultiRoleGetPermissionsMatrix200Response> {
        var localVariablePath = "/api/projects/{projectId}/permissions-matrix"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MultiRoleGetPermissionsMatrix200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Simulate app-role feature permission for a path
     
     - parameter projectId: (path) Project ID used to resolve role configuration. 
     - parameter multiRoleSimulateAppPermissionsRequest: (body) Role slug plus either OpenAPI &#x60;operationId&#x60; or HTTP &#x60;method&#x60; and &#x60;pathname&#x60; to evaluate. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func multiRoleSimulateAppPermissions(projectId: String, multiRoleSimulateAppPermissionsRequest: MultiRoleSimulateAppPermissionsRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return multiRoleSimulateAppPermissionsWithRequestBuilder(projectId: projectId, multiRoleSimulateAppPermissionsRequest: multiRoleSimulateAppPermissionsRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Simulate app-role feature permission for a path
     - POST /api/projects/{projectId}/multi-role/simulate-permissions
     - Given role slug and either `operationId` or HTTP method + pathname, returns whether `featurePermissions` would allow gated routes. Unmapped paths or unknown operation IDs return allowed with `no_feature_gate_for_path` or `no_feature_gate_for_operation_id`.
     - Bearer Token:
       - type: http
       - name: BearerToken
     - parameter projectId: (path) Project ID used to resolve role configuration. 
     - parameter multiRoleSimulateAppPermissionsRequest: (body) Role slug plus either OpenAPI &#x60;operationId&#x60; or HTTP &#x60;method&#x60; and &#x60;pathname&#x60; to evaluate. 
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func multiRoleSimulateAppPermissionsWithRequestBuilder(projectId: String, multiRoleSimulateAppPermissionsRequest: MultiRoleSimulateAppPermissionsRequest) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/projects/{projectId}/multi-role/simulate-permissions"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: multiRoleSimulateAppPermissionsRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Toggle role on/off
     
     - parameter projectId: (path) Project ID. 
     - parameter roleSlug: (path) Role slug to toggle (e.g. starter &#x60;customer&#x60; or a role you added). 
     - parameter multiRoleToggleRoleRequest: (body) Whether the role is enabled (true) or disabled (false). 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func multiRoleToggleRole(projectId: String, roleSlug: String, multiRoleToggleRoleRequest: MultiRoleToggleRoleRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MultiRoleToggleRole200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return multiRoleToggleRoleWithRequestBuilder(projectId: projectId, roleSlug: roleSlug, multiRoleToggleRoleRequest: multiRoleToggleRoleRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Toggle role on/off
     - PATCH /api/projects/{projectId}/multi-role/roles/{roleSlug}/toggle
     - Enable or disable a role for the project. When disabled, the role is no longer available for signup or assignment.
     - Bearer Token:
       - type: http
       - name: BearerToken
     - parameter projectId: (path) Project ID. 
     - parameter roleSlug: (path) Role slug to toggle (e.g. starter &#x60;customer&#x60; or a role you added). 
     - parameter multiRoleToggleRoleRequest: (body) Whether the role is enabled (true) or disabled (false). 
     - returns: RequestBuilder<MultiRoleToggleRole200Response> 
     */
    open class func multiRoleToggleRoleWithRequestBuilder(projectId: String, roleSlug: String, multiRoleToggleRoleRequest: MultiRoleToggleRoleRequest) -> RequestBuilder<MultiRoleToggleRole200Response> {
        var localVariablePath = "/api/projects/{projectId}/multi-role/roles/{roleSlug}/toggle"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let roleSlugPreEscape = "\(APIHelper.mapValueToPathItem(roleSlug))"
        let roleSlugPostEscape = roleSlugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{roleSlug}", with: roleSlugPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: multiRoleToggleRoleRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MultiRoleToggleRole200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update collection permissions for a role
     
     - parameter projectId: (path) Project ID. 
     - parameter roleSlug: (path) Role slug (e.g. starter &#x60;customer&#x60; or a role you added). 
     - parameter collectionId: (path) Collection ID to set permissions for. 
     - parameter multiRoleUpdateCollectionPermissionsRequest: (body) Allowed actions and optional conditions for the role on this collection. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func multiRoleUpdateCollectionPermissions(projectId: String, roleSlug: String, collectionId: String, multiRoleUpdateCollectionPermissionsRequest: MultiRoleUpdateCollectionPermissionsRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MultiRoleToggleRole200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return multiRoleUpdateCollectionPermissionsWithRequestBuilder(projectId: projectId, roleSlug: roleSlug, collectionId: collectionId, multiRoleUpdateCollectionPermissionsRequest: multiRoleUpdateCollectionPermissionsRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update collection permissions for a role
     - PATCH /api/projects/{projectId}/multi-role/roles/{roleSlug}/collections/{collectionId}/permissions
     - Update collection-specific permissions for a role in a project. Accepts BearerToken (JWT) or ApiKeyAuth (X-API-Key). 
     - Bearer Token:
       - type: http
       - name: BearerToken
     - parameter projectId: (path) Project ID. 
     - parameter roleSlug: (path) Role slug (e.g. starter &#x60;customer&#x60; or a role you added). 
     - parameter collectionId: (path) Collection ID to set permissions for. 
     - parameter multiRoleUpdateCollectionPermissionsRequest: (body) Allowed actions and optional conditions for the role on this collection. 
     - returns: RequestBuilder<MultiRoleToggleRole200Response> 
     */
    open class func multiRoleUpdateCollectionPermissionsWithRequestBuilder(projectId: String, roleSlug: String, collectionId: String, multiRoleUpdateCollectionPermissionsRequest: MultiRoleUpdateCollectionPermissionsRequest) -> RequestBuilder<MultiRoleToggleRole200Response> {
        var localVariablePath = "/api/projects/{projectId}/multi-role/roles/{roleSlug}/collections/{collectionId}/permissions"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let roleSlugPreEscape = "\(APIHelper.mapValueToPathItem(roleSlug))"
        let roleSlugPostEscape = roleSlugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{roleSlug}", with: roleSlugPostEscape, options: .literal, range: nil)
        let collectionIdPreEscape = "\(APIHelper.mapValueToPathItem(collectionId))"
        let collectionIdPostEscape = collectionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{collectionId}", with: collectionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: multiRoleUpdateCollectionPermissionsRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MultiRoleToggleRole200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update role configuration
     
     - parameter projectId: (path) Project ID. 
     - parameter roleSlug: (path) Role slug to update (e.g. starter &#x60;customer&#x60; or a role you added). 
     - parameter multiRoleUpdateRoleRequest: (body) Same fields as **Add custom role** — send only fields you want to change. &#x60;defaultPermissions&#x60; / &#x60;collectionPermissions&#x60; are normalized the same way as on create. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func multiRoleUpdateRole(projectId: String, roleSlug: String, multiRoleUpdateRoleRequest: MultiRoleUpdateRoleRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MultiRoleToggleRole200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return multiRoleUpdateRoleWithRequestBuilder(projectId: projectId, roleSlug: roleSlug, multiRoleUpdateRoleRequest: multiRoleUpdateRoleRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update role configuration
     - PATCH /api/projects/{projectId}/multi-role/roles/{roleSlug}
     - Update an app role — same fields as **Add custom role** (partial). `defaultPermissions` / `collectionPermissions` use the same normalization as on create. **featurePermissions:** see schema `AppRoleFeaturePermissions`.
     - Bearer Token:
       - type: http
       - name: BearerToken
     - parameter projectId: (path) Project ID. 
     - parameter roleSlug: (path) Role slug to update (e.g. starter &#x60;customer&#x60; or a role you added). 
     - parameter multiRoleUpdateRoleRequest: (body) Same fields as **Add custom role** — send only fields you want to change. &#x60;defaultPermissions&#x60; / &#x60;collectionPermissions&#x60; are normalized the same way as on create. 
     - returns: RequestBuilder<MultiRoleToggleRole200Response> 
     */
    open class func multiRoleUpdateRoleWithRequestBuilder(projectId: String, roleSlug: String, multiRoleUpdateRoleRequest: MultiRoleUpdateRoleRequest) -> RequestBuilder<MultiRoleToggleRole200Response> {
        var localVariablePath = "/api/projects/{projectId}/multi-role/roles/{roleSlug}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let roleSlugPreEscape = "\(APIHelper.mapValueToPathItem(roleSlug))"
        let roleSlugPostEscape = roleSlugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{roleSlug}", with: roleSlugPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: multiRoleUpdateRoleRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MultiRoleToggleRole200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update multi-role feature settings
     
     - parameter projectId: (path) Project ID. 
     - parameter multiRoleUpdateSettingsRequest: (body) Feature flags only — not per-role approval. Use &#x60;settings.allowMultipleRoles&#x60;, &#x60;requireRoleSelection&#x60;, &#x60;autoAssignDefault&#x60;, &#x60;dataOwnerField&#x60;. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func multiRoleUpdateSettings(projectId: String, multiRoleUpdateSettingsRequest: MultiRoleUpdateSettingsRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: MultiRoleUpdateSettings200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return multiRoleUpdateSettingsWithRequestBuilder(projectId: projectId, multiRoleUpdateSettingsRequest: multiRoleUpdateSettingsRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update multi-role feature settings
     - PATCH /api/projects/{projectId}/multi-role/settings
     - Update multi-role feature settings: enable/disable the feature, `defaultRole`, and `settings` (`allowMultipleRoles`, `requireRoleSelection`, `autoAssignDefault`, `dataOwnerField`). Does not edit role definitions — use `POST/PATCH .../multi-role/roles` (same body shape as add role). Accepts BearerToken (JWT) or ApiKeyAuth (X-API-Key). 
     - Bearer Token:
       - type: http
       - name: BearerToken
     - parameter projectId: (path) Project ID. 
     - parameter multiRoleUpdateSettingsRequest: (body) Feature flags only — not per-role approval. Use &#x60;settings.allowMultipleRoles&#x60;, &#x60;requireRoleSelection&#x60;, &#x60;autoAssignDefault&#x60;, &#x60;dataOwnerField&#x60;. 
     - returns: RequestBuilder<MultiRoleUpdateSettings200Response> 
     */
    open class func multiRoleUpdateSettingsWithRequestBuilder(projectId: String, multiRoleUpdateSettingsRequest: MultiRoleUpdateSettingsRequest) -> RequestBuilder<MultiRoleUpdateSettings200Response> {
        var localVariablePath = "/api/projects/{projectId}/multi-role/settings"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: multiRoleUpdateSettingsRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MultiRoleUpdateSettings200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
