//
// RoleElevationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RoleElevationAPI {

    /**
     Approve/reject role elevation request (admin only)
     
     - parameter orgId: (path)  
     - parameter requestId: (path)  
     - parameter approveRoleElevationRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func approveRoleElevation(orgId: String, requestId: String, approveRoleElevationRequest: ApproveRoleElevationRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: ApproveRoleElevation200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return approveRoleElevationWithRequestBuilder(orgId: orgId, requestId: requestId, approveRoleElevationRequest: approveRoleElevationRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Approve/reject role elevation request (admin only)
     - POST /api/orgs/{orgId}/role-elevation/{requestId}/approve
     - Admin approves or rejects a role elevation request
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter orgId: (path)  
     - parameter requestId: (path)  
     - parameter approveRoleElevationRequest: (body)  
     - returns: RequestBuilder<ApproveRoleElevation200Response> 
     */
    open class func approveRoleElevationWithRequestBuilder(orgId: String, requestId: String, approveRoleElevationRequest: ApproveRoleElevationRequest) -> RequestBuilder<ApproveRoleElevation200Response> {
        var localVariablePath = "/api/orgs/{orgId}/role-elevation/{requestId}/approve"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let requestIdPreEscape = "\(APIHelper.mapValueToPathItem(requestId))"
        let requestIdPostEscape = requestIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{requestId}", with: requestIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: approveRoleElevationRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApproveRoleElevation200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter status
     */
    public enum Status_getPendingRoleElevationRequests: String, CaseIterable {
        case pending = "pending"
        case approved = "approved"
        case rejected = "rejected"
    }

    /**
     Get pending role elevation requests (admin only)
     
     - parameter orgId: (path)  
     - parameter status: (query)  (optional, default to .pending)
     - parameter page: (query)  (optional, default to 1)
     - parameter limit: (query)  (optional, default to 50)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getPendingRoleElevationRequests(orgId: String, status: Status_getPendingRoleElevationRequests? = nil, page: Int? = nil, limit: Int? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetPendingRoleElevationRequests200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getPendingRoleElevationRequestsWithRequestBuilder(orgId: orgId, status: status, page: page, limit: limit).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get pending role elevation requests (admin only)
     - GET /api/orgs/{orgId}/role-elevation/pending
     - Get all pending role elevation requests requiring admin approval
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter orgId: (path)  
     - parameter status: (query)  (optional, default to .pending)
     - parameter page: (query)  (optional, default to 1)
     - parameter limit: (query)  (optional, default to 50)
     - returns: RequestBuilder<GetPendingRoleElevationRequests200Response> 
     */
    open class func getPendingRoleElevationRequestsWithRequestBuilder(orgId: String, status: Status_getPendingRoleElevationRequests? = nil, page: Int? = nil, limit: Int? = nil) -> RequestBuilder<GetPendingRoleElevationRequests200Response> {
        var localVariablePath = "/api/orgs/{orgId}/role-elevation/pending"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetPendingRoleElevationRequests200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get role elevation status
     
     - parameter projectId: (path)  
     - parameter roleSlug: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getRoleElevationStatus(projectId: String, roleSlug: String? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetRoleElevationStatus200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getRoleElevationStatusWithRequestBuilder(projectId: projectId, roleSlug: roleSlug).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get role elevation status
     - GET /api/projects/{projectId}/role-elevation/status
     - Get status of pending role elevation requests for current user
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter roleSlug: (query)  (optional)
     - returns: RequestBuilder<GetRoleElevationStatus200Response> 
     */
    open class func getRoleElevationStatusWithRequestBuilder(projectId: String, roleSlug: String? = nil) -> RequestBuilder<GetRoleElevationStatus200Response> {
        var localVariablePath = "/api/projects/{projectId}/role-elevation/status"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "roleSlug": (wrappedValue: roleSlug?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRoleElevationStatus200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Request role elevation
     
     - parameter projectId: (path)  
     - parameter requestRoleElevationRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func requestRoleElevation(projectId: String, requestRoleElevationRequest: RequestRoleElevationRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: RequestRoleElevation200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return requestRoleElevationWithRequestBuilder(projectId: projectId, requestRoleElevationRequest: requestRoleElevationRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Request role elevation
     - POST /api/projects/{projectId}/role-elevation/request
     - User requests to upgrade to a specific role. May require payment, KYC, or admin approval based on role configuration.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter requestRoleElevationRequest: (body)  
     - returns: RequestBuilder<RequestRoleElevation200Response> 
     */
    open class func requestRoleElevationWithRequestBuilder(projectId: String, requestRoleElevationRequest: RequestRoleElevationRequest) -> RequestBuilder<RequestRoleElevation200Response> {
        var localVariablePath = "/api/projects/{projectId}/role-elevation/request"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestRoleElevationRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RequestRoleElevation200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Upload verification documents
     
     - parameter projectId: (path)  
     - parameter uploadVerificationDocumentsRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func uploadVerificationDocuments(projectId: String, uploadVerificationDocumentsRequest: UploadVerificationDocumentsRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return uploadVerificationDocumentsWithRequestBuilder(projectId: projectId, uploadVerificationDocumentsRequest: uploadVerificationDocumentsRequest).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Upload verification documents
     - POST /api/projects/{projectId}/role-elevation/documents
     - Upload KYC/verification documents for role elevation
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter uploadVerificationDocumentsRequest: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func uploadVerificationDocumentsWithRequestBuilder(projectId: String, uploadVerificationDocumentsRequest: UploadVerificationDocumentsRequest) -> RequestBuilder<Void> {
        var localVariablePath = "/api/projects/{projectId}/role-elevation/documents"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: uploadVerificationDocumentsRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = MudbaseSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
