//
// RolesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RolesAPI {

    /**
     ~~Assign custom role to user~~ (deprecated)
     
     - parameter orgId: (path)  
     - parameter userId: (path)  
     - parameter assignRoleRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @discardableResult
    open class func assignRole(orgId: String, userId: String, assignRoleRequest: AssignRoleRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: AssignRole200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return assignRoleWithRequestBuilder(orgId: orgId, userId: userId, assignRoleRequest: assignRoleRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     ~~Assign custom role to user~~ (deprecated)
     - POST /api/orgs/{orgId}/users/{userId}/role
     - Assign a custom role to a user in the organization. Requires JWT Bearer token authentication. Both OrgBearerAuth and ProjectBearerAuth are supported (they use the same JWT token format). These are organization-level operations. 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter orgId: (path)  
     - parameter userId: (path)  
     - parameter assignRoleRequest: (body)  
     - returns: RequestBuilder<AssignRole200Response> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func assignRoleWithRequestBuilder(orgId: String, userId: String, assignRoleRequest: AssignRoleRequest) -> RequestBuilder<AssignRole200Response> {
        var localVariablePath = "/api/orgs/{orgId}/users/{userId}/role"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{userId}", with: userIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: assignRoleRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AssignRole200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     ~~Check user permissions~~ (deprecated)
     
     - parameter orgId: (path)  
     - parameter userId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @discardableResult
    open class func checkPermissions(orgId: String, userId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: CheckPermissions200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return checkPermissionsWithRequestBuilder(orgId: orgId, userId: userId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     ~~Check user permissions~~ (deprecated)
     - GET /api/orgs/{orgId}/users/{userId}/permissions
     - Get all permissions for a user (system + custom role combined)
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter orgId: (path)  
     - parameter userId: (path)  
     - returns: RequestBuilder<CheckPermissions200Response> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func checkPermissionsWithRequestBuilder(orgId: String, userId: String) -> RequestBuilder<CheckPermissions200Response> {
        var localVariablePath = "/api/orgs/{orgId}/users/{userId}/permissions"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{userId}", with: userIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CheckPermissions200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     ~~Create custom role~~ (deprecated)
     
     - parameter orgId: (path)  
     - parameter createRoleRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @discardableResult
    open class func createRole(orgId: String, createRoleRequest: CreateRoleRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: CreateRole201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return createRoleWithRequestBuilder(orgId: orgId, createRoleRequest: createRoleRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     ~~Create custom role~~ (deprecated)
     - POST /api/orgs/{orgId}/roles
     - Create a new custom role with specific permissions for your organization. Requires JWT Bearer token authentication. Both OrgBearerAuth and ProjectBearerAuth are supported (they use the same JWT token format). These are organization-level operations. 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter orgId: (path)  
     - parameter createRoleRequest: (body)  
     - returns: RequestBuilder<CreateRole201Response> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func createRoleWithRequestBuilder(orgId: String, createRoleRequest: CreateRoleRequest) -> RequestBuilder<CreateRole201Response> {
        var localVariablePath = "/api/orgs/{orgId}/roles"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createRoleRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateRole201Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     ~~Delete role~~ (deprecated)
     
     - parameter orgId: (path)  
     - parameter roleId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @discardableResult
    open class func deleteRole(orgId: String, roleId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: DeleteRole200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteRoleWithRequestBuilder(orgId: orgId, roleId: roleId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     ~~Delete role~~ (deprecated)
     - DELETE /api/orgs/{orgId}/roles/{roleId}
     - Delete a custom role. Cannot delete system roles or roles with active users. Requires JWT Bearer token authentication. Both OrgBearerAuth and ProjectBearerAuth are supported (they use the same JWT token format). These are organization-level operations. 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter orgId: (path)  
     - parameter roleId: (path)  
     - returns: RequestBuilder<DeleteRole200Response> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func deleteRoleWithRequestBuilder(orgId: String, roleId: String) -> RequestBuilder<DeleteRole200Response> {
        var localVariablePath = "/api/orgs/{orgId}/roles/{roleId}"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let roleIdPreEscape = "\(APIHelper.mapValueToPathItem(roleId))"
        let roleIdPostEscape = roleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{roleId}", with: roleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteRole200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     ~~Get role details~~ (deprecated)
     
     - parameter orgId: (path)  
     - parameter roleId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @discardableResult
    open class func getRole(orgId: String, roleId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetRole200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getRoleWithRequestBuilder(orgId: orgId, roleId: roleId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     ~~Get role details~~ (deprecated)
     - GET /api/orgs/{orgId}/roles/{roleId}
     - Get details of a specific custom role. Requires: OrgBearerAuth (organization-level authentication only). 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - parameter orgId: (path)  
     - parameter roleId: (path)  
     - returns: RequestBuilder<GetRole200Response> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func getRoleWithRequestBuilder(orgId: String, roleId: String) -> RequestBuilder<GetRole200Response> {
        var localVariablePath = "/api/orgs/{orgId}/roles/{roleId}"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let roleIdPreEscape = "\(APIHelper.mapValueToPathItem(roleId))"
        let roleIdPostEscape = roleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{roleId}", with: roleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRole200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     ~~Get users with specific role~~ (deprecated)
     
     - parameter orgId: (path)  
     - parameter roleSlug: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @discardableResult
    open class func getUsersByRole(orgId: String, roleSlug: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetUsersByRole200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getUsersByRoleWithRequestBuilder(orgId: orgId, roleSlug: roleSlug).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     ~~Get users with specific role~~ (deprecated)
     - GET /api/orgs/{orgId}/roles/{roleSlug}/users
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter orgId: (path)  
     - parameter roleSlug: (path)  
     - returns: RequestBuilder<GetUsersByRole200Response> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func getUsersByRoleWithRequestBuilder(orgId: String, roleSlug: String) -> RequestBuilder<GetUsersByRole200Response> {
        var localVariablePath = "/api/orgs/{orgId}/roles/{roleSlug}/users"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let roleSlugPreEscape = "\(APIHelper.mapValueToPathItem(roleSlug))"
        let roleSlugPostEscape = roleSlugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{roleSlug}", with: roleSlugPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetUsersByRole200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     ~~List all roles~~ (deprecated)
     
     - parameter orgId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @discardableResult
    open class func listRoles(orgId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: ListRoles200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return listRolesWithRequestBuilder(orgId: orgId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     ~~List all roles~~ (deprecated)
     - GET /api/orgs/{orgId}/roles
     - Get all custom roles for the organization. Requires: OrgBearerAuth (organization-level authentication only). 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - parameter orgId: (path)  
     - returns: RequestBuilder<ListRoles200Response> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func listRolesWithRequestBuilder(orgId: String) -> RequestBuilder<ListRoles200Response> {
        var localVariablePath = "/api/orgs/{orgId}/roles"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListRoles200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     ~~Remove custom role from user~~ (deprecated)
     
     - parameter orgId: (path)  
     - parameter userId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @discardableResult
    open class func removeRole(orgId: String, userId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: AssignRole200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return removeRoleWithRequestBuilder(orgId: orgId, userId: userId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     ~~Remove custom role from user~~ (deprecated)
     - DELETE /api/orgs/{orgId}/users/{userId}/role
     - Remove a custom role from a user in the organization. Requires JWT Bearer token authentication. Both OrgBearerAuth and ProjectBearerAuth are supported (they use the same JWT token format). These are organization-level operations. 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter orgId: (path)  
     - parameter userId: (path)  
     - returns: RequestBuilder<AssignRole200Response> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func removeRoleWithRequestBuilder(orgId: String, userId: String) -> RequestBuilder<AssignRole200Response> {
        var localVariablePath = "/api/orgs/{orgId}/users/{userId}/role"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{userId}", with: userIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AssignRole200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     ~~Update role~~ (deprecated)
     
     - parameter orgId: (path)  
     - parameter roleId: (path)  
     - parameter updateRoleRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @discardableResult
    open class func updateRole(orgId: String, roleId: String, updateRoleRequest: UpdateRoleRequest, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: UpdateRole200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return updateRoleWithRequestBuilder(orgId: orgId, roleId: roleId, updateRoleRequest: updateRoleRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     ~~Update role~~ (deprecated)
     - PUT /api/orgs/{orgId}/roles/{roleId}
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter orgId: (path)  
     - parameter roleId: (path)  
     - parameter updateRoleRequest: (body)  
     - returns: RequestBuilder<UpdateRole200Response> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func updateRoleWithRequestBuilder(orgId: String, roleId: String, updateRoleRequest: UpdateRoleRequest) -> RequestBuilder<UpdateRole200Response> {
        var localVariablePath = "/api/orgs/{orgId}/roles/{roleId}"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let roleIdPreEscape = "\(APIHelper.mapValueToPathItem(roleId))"
        let roleIdPostEscape = roleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{roleId}", with: roleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateRoleRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UpdateRole200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
