//
// UsageAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class UsageAPI {

    /**
     Get current overage line items
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getOverage(apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetOverage200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getOverageWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get current overage line items
     - GET /api/usage/overage
     - Returns overage line items for the authenticated organization's current billing period (current month). Used by dashboards and billing UIs. Requires org-level JWT (authRequired). 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - returns: RequestBuilder<GetOverage200Response> 
     */
    open class func getOverageWithRequestBuilder() -> RequestBuilder<GetOverage200Response> {
        let localVariablePath = "/api/usage/overage"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetOverage200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter period
     */
    public enum Period_getProjectUsageStats: String, CaseIterable {
        case day = "day"
        case week = "week"
        case month = "month"
    }

    /**
     Get project usage
     
     - parameter projectId: (path)  
     - parameter period: (query)  (optional, default to .month)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getProjectUsageStats(projectId: String, period: Period_getProjectUsageStats? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: ProjectUsageStatsResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getProjectUsageStatsWithRequestBuilder(projectId: projectId, period: period).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get project usage
     - GET /api/usage/projects/{projectId}
     - Get usage statistics for a project (API calls, storage, bandwidth, database operations). Accepts: OrgBearerAuth (for admin users), ProjectBearerAuth (JWT for authenticated users), or ApiKeyAuth (X-API-Key for programmatic access). Both ProjectBearerAuth and ApiKeyAuth are fully implemented. 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter period: (query)  (optional, default to .month)
     - returns: RequestBuilder<ProjectUsageStatsResponse> 
     */
    open class func getProjectUsageStatsWithRequestBuilder(projectId: String, period: Period_getProjectUsageStats? = nil) -> RequestBuilder<ProjectUsageStatsResponse> {
        var localVariablePath = "/api/usage/projects/{projectId}"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "period": (wrappedValue: period?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProjectUsageStatsResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Project dashboard usage summary
     
     - parameter projectId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getProjectUsageSummary(projectId: String, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: ProjectUsageSummaryResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getProjectUsageSummaryWithRequestBuilder(projectId: projectId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Project dashboard usage summary
     - GET /api/usage/projects/{projectId}/summary
     - Lightweight dashboard metrics for a project: requests today vs yesterday with % change, active users (24h/7d/30d), 7d active-user trend, 14-day request volume series, per-project openapi-docs latency (today/7d), and uptime (30d) from org HTTP non-5xx when enough samples else DB heartbeats. Same auth as GET /api/usage/projects/{projectId} (org JWT, project JWT, or API key scoped to the project). 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - returns: RequestBuilder<ProjectUsageSummaryResponse> 
     */
    open class func getProjectUsageSummaryWithRequestBuilder(projectId: String) -> RequestBuilder<ProjectUsageSummaryResponse> {
        var localVariablePath = "/api/usage/projects/{projectId}/summary"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProjectUsageSummaryResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter period
     */
    public enum Period_getUsage: String, CaseIterable {
        case day = "day"
        case week = "week"
        case month = "month"
        case year = "year"
    }

    /**
     Get organization usage
     
     - parameter period: (query)  (optional, default to .month)
     - parameter startDate: (query)  (optional)
     - parameter endDate: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getUsage(period: Period_getUsage? = nil, startDate: Date? = nil, endDate: Date? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: UsageStatsResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getUsageWithRequestBuilder(period: period, startDate: startDate, endDate: endDate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get organization usage
     - GET /api/usage
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter period: (query)  (optional, default to .month)
     - parameter startDate: (query)  (optional)
     - parameter endDate: (query)  (optional)
     - returns: RequestBuilder<UsageStatsResponse> 
     */
    open class func getUsageWithRequestBuilder(period: Period_getUsage? = nil, startDate: Date? = nil, endDate: Date? = nil) -> RequestBuilder<UsageStatsResponse> {
        let localVariablePath = "/api/usage"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "period": (wrappedValue: period?.encodeToJSON(), isExplode: true),
            "startDate": (wrappedValue: startDate?.encodeToJSON(), isExplode: true),
            "endDate": (wrappedValue: endDate?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UsageStatsResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get usage trends
     
     - parameter days: (query)  (optional, default to 30)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getUsageTrends(days: Int? = nil, apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: UsageTrendsResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return getUsageTrendsWithRequestBuilder(days: days).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get usage trends
     - GET /api/usage/trends
     - Get usage trends over time for the authenticated organization or project. Accepts: OrgBearerAuth (for admin users), ProjectBearerAuth (JWT for authenticated users), or ApiKeyAuth (X-API-Key for programmatic access). Both ProjectBearerAuth and ApiKeyAuth are fully implemented. 
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter days: (query)  (optional, default to 30)
     - returns: RequestBuilder<UsageTrendsResponse> 
     */
    open class func getUsageTrendsWithRequestBuilder(days: Int? = nil) -> RequestBuilder<UsageTrendsResponse> {
        let localVariablePath = "/api/usage/trends"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "days": (wrappedValue: days?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UsageTrendsResponse>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get usage warnings
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getUsageWarnings(apiResponseQueue: DispatchQueue = MudbaseSDKAPI.apiResponseQueue, completion: @escaping ((_ data: GetUsageWarnings200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return getUsageWarningsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get usage warnings
     - GET /api/usage/warnings
     - Returns usage warnings for the authenticated org (e.g. at 80% and 95% of plan limits). Requires org-level JWT.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - returns: RequestBuilder<GetUsageWarnings200Response> 
     */
    open class func getUsageWarningsWithRequestBuilder() -> RequestBuilder<GetUsageWarnings200Response> {
        let localVariablePath = "/api/usage/warnings"
        let localVariableURLString = MudbaseSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetUsageWarnings200Response>.Type = MudbaseSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
