//
// AdminPlatformDnsVerificationPatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminPlatformDnsVerificationPatchRequest: Codable, JSONEncodable, Hashable {

    public static let recordTypeRule = StringRule(minLength: nil, maxLength: 32, pattern: nil)
    public static let recordNameRule = StringRule(minLength: nil, maxLength: 512, pattern: nil)
    public static let recordValueRule = StringRule(minLength: nil, maxLength: 4096, pattern: nil)
    public static let ttlSecondsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 86400, exclusiveMaximum: false, multipleOf: nil)
    public static let staffNoteRule = StringRule(minLength: nil, maxLength: 4000, pattern: nil)
    public var recordType: String?
    public var recordName: String
    public var recordValue: String
    public var ttlSeconds: Int?
    public var staffNote: String?
    public var resetCustomerPlatformDnsSubmission: Bool?
    /** When not false (default), email org billing contact with step-3 DNS instructions after save. */
    public var notifyOrg: Bool?

    public init(recordType: String? = nil, recordName: String, recordValue: String, ttlSeconds: Int? = nil, staffNote: String? = nil, resetCustomerPlatformDnsSubmission: Bool? = nil, notifyOrg: Bool? = nil) {
        self.recordType = recordType
        self.recordName = recordName
        self.recordValue = recordValue
        self.ttlSeconds = ttlSeconds
        self.staffNote = staffNote
        self.resetCustomerPlatformDnsSubmission = resetCustomerPlatformDnsSubmission
        self.notifyOrg = notifyOrg
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recordType
        case recordName
        case recordValue
        case ttlSeconds
        case staffNote
        case resetCustomerPlatformDnsSubmission
        case notifyOrg
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(recordType, forKey: .recordType)
        try container.encode(recordName, forKey: .recordName)
        try container.encode(recordValue, forKey: .recordValue)
        try container.encodeIfPresent(ttlSeconds, forKey: .ttlSeconds)
        try container.encodeIfPresent(staffNote, forKey: .staffNote)
        try container.encodeIfPresent(resetCustomerPlatformDnsSubmission, forKey: .resetCustomerPlatformDnsSubmission)
        try container.encodeIfPresent(notifyOrg, forKey: .notifyOrg)
    }
}

