//
// ApiKycWebhookConfigGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiKycWebhookConfigGet200Response: Codable, JSONEncodable, Hashable {

    public var webhookUrl: String?
    public var secretSet: Bool?

    public init(webhookUrl: String? = nil, secretSet: Bool? = nil) {
        self.webhookUrl = webhookUrl
        self.secretSet = secretSet
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case webhookUrl
        case secretSet
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(webhookUrl, forKey: .webhookUrl)
        try container.encodeIfPresent(secretSet, forKey: .secretSet)
    }
}

