//
// ApiMeBootstrapGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiMeBootstrapGet200Response: Codable, JSONEncodable, Hashable {

    public var user: AnyCodable?
    public var organizations: [AnyCodable]?
    public var defaultOrg: AnyCodable?
    public var projects: [AnyCodable]?

    public init(user: AnyCodable? = nil, organizations: [AnyCodable]? = nil, defaultOrg: AnyCodable? = nil, projects: [AnyCodable]? = nil) {
        self.user = user
        self.organizations = organizations
        self.defaultOrg = defaultOrg
        self.projects = projects
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case organizations
        case defaultOrg
        case projects
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(organizations, forKey: .organizations)
        try container.encodeIfPresent(defaultOrg, forKey: .defaultOrg)
        try container.encodeIfPresent(projects, forKey: .projects)
    }
}

