//
// ApproveRoleElevation200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApproveRoleElevation200Response: Codable, JSONEncodable, Hashable {

    public var message: String?
    public var request: AnyCodable?

    public init(message: String? = nil, request: AnyCodable? = nil) {
        self.message = message
        self.request = request
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case request
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(request, forKey: .request)
    }
}

