//
// AppRoleCollectionCrudAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A single CRUD-style action on a collection. */
public enum AppRoleCollectionCrudAction: String, Codable, CaseIterable {
    case create = "create"
    case read = "read"
    case update = "update"
    case delete = "delete"
}
