//
// AuthGetOAuthProviders200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthGetOAuthProviders200Response: Codable, JSONEncodable, Hashable {

    public var providers: [AuthGetOAuthProviders200ResponseProvidersInner]?
    public var total: Int?

    public init(providers: [AuthGetOAuthProviders200ResponseProvidersInner]? = nil, total: Int? = nil) {
        self.providers = providers
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case providers
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(providers, forKey: .providers)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

