//
// AuthResendVerificationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthResendVerificationRequest: Codable, JSONEncodable, Hashable {

    public var email: String
    /** Optional; for project-scoped signup (sends link with project context) */
    public var projectId: String?

    public init(email: String, projectId: String? = nil) {
        self.email = email
        self.projectId = projectId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case projectId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(projectId, forKey: .projectId)
    }
}

