//
// AuthLogin200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthLogin200Response: Codable, JSONEncodable, Hashable {

    public var message: String?
    /** JWT access token (use in Authorization Bearer header) */
    public var token: String?
    /** JWT refresh token (use with POST /api/auth/refresh to get new token pair) */
    public var refreshToken: String?
    /** Access token TTL in seconds (e.g. 1800 for 30 minutes) */
    public var expiresIn: Int?
    public var user: AuthLogin200ResponseUser?

    public init(message: String? = nil, token: String? = nil, refreshToken: String? = nil, expiresIn: Int? = nil, user: AuthLogin200ResponseUser? = nil) {
        self.message = message
        self.token = token
        self.refreshToken = refreshToken
        self.expiresIn = expiresIn
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case token
        case refreshToken
        case expiresIn
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(refreshToken, forKey: .refreshToken)
        try container.encodeIfPresent(expiresIn, forKey: .expiresIn)
        try container.encodeIfPresent(user, forKey: .user)
    }
}

