//
// AuthConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Project auth configuration (providers, notifyOnNewSignIn). */
public struct AuthConfig: Codable, JSONEncodable, Hashable {

    public var providers: [AuthProvider]?
    /** When true, a \"new sign-in detected\" email is sent to the user on each app sign-in (local or OAuth). Counts against the org's messaging/email plan quota. Default false. Organization-based sign-in always sends this email (no quota deduction).  */
    public var notifyOnNewSignIn: Bool? = false

    public init(providers: [AuthProvider]? = nil, notifyOnNewSignIn: Bool? = false) {
        self.providers = providers
        self.notifyOnNewSignIn = notifyOnNewSignIn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case providers
        case notifyOnNewSignIn
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(providers, forKey: .providers)
        try container.encodeIfPresent(notifyOnNewSignIn, forKey: .notifyOnNewSignIn)
    }
}

