//
// AuthRefresh200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthRefresh200Response: Codable, JSONEncodable, Hashable {

    public var message: String?
    /** New JWT access token */
    public var token: String?
    /** New refresh token (store and use for next refresh) */
    public var refreshToken: String?
    /** Access token TTL in seconds */
    public var expiresIn: Int?

    public init(message: String? = nil, token: String? = nil, refreshToken: String? = nil, expiresIn: Int? = nil) {
        self.message = message
        self.token = token
        self.refreshToken = refreshToken
        self.expiresIn = expiresIn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case token
        case refreshToken
        case expiresIn
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(refreshToken, forKey: .refreshToken)
        try container.encodeIfPresent(expiresIn, forKey: .expiresIn)
    }
}

