//
// AuthVerifyEmailRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthVerifyEmailRequest: Codable, JSONEncodable, Hashable {

    /** Verification token from the email link */
    public var token: String
    /** Optional; for project signup context (redirect hint) */
    public var projectId: String?

    public init(token: String, projectId: String? = nil) {
        self.token = token
        self.projectId = projectId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case projectId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
        try container.encodeIfPresent(projectId, forKey: .projectId)
    }
}

