//
// AuthRegister429Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthRegister429Response: Codable, JSONEncodable, Hashable {

    /** Exact error message from the backend */
    public var error: String
    public var code: String?
    public var details: ErrorDetails?
    public var timestamp: Date?
    public var path: String?
    public var requestId: String?
    public var retryAfter: Int?

    public init(error: String, code: String? = nil, details: ErrorDetails? = nil, timestamp: Date? = nil, path: String? = nil, requestId: String? = nil, retryAfter: Int? = nil) {
        self.error = error
        self.code = code
        self.details = details
        self.timestamp = timestamp
        self.path = path
        self.requestId = requestId
        self.retryAfter = retryAfter
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case code
        case details
        case timestamp
        case path
        case requestId
        case retryAfter
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(error, forKey: .error)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(details, forKey: .details)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(retryAfter, forKey: .retryAfter)
    }
}

