//
// AuthOauthCallback200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthOauthCallback200Response: Codable, JSONEncodable, Hashable {

    public var token: String?
    public var user: User?

    public init(token: String? = nil, user: User? = nil) {
        self.token = token
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(user, forKey: .user)
    }
}

