//
// BillingGetPublicPlans200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BillingGetPublicPlans200Response: Codable, JSONEncodable, Hashable {

    public var plans: [Plan]?

    public init(plans: [Plan]? = nil) {
        self.plans = plans
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case plans
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(plans, forKey: .plans)
    }
}

