//
// BillingHandleFlutterwaveWebhookRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BillingHandleFlutterwaveWebhookRequest: Codable, JSONEncodable, Hashable {

    /** Event type (e.g. charge.completed, payment.successful) */
    public var event: String?
    public var data: BillingHandleFlutterwaveWebhookRequestData?

    public init(event: String? = nil, data: BillingHandleFlutterwaveWebhookRequestData? = nil) {
        self.event = event
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case event
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(event, forKey: .event)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

