//
// ChatList200ResponseDataChatsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChatList200ResponseDataChatsInner: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var name: String?
    public var type: String?
    public var lastMessage: ChatList200ResponseDataChatsInnerLastMessage?
    public var unreadCount: Int?

    public init(id: String? = nil, name: String? = nil, type: String? = nil, lastMessage: ChatList200ResponseDataChatsInnerLastMessage? = nil, unreadCount: Int? = nil) {
        self.id = id
        self.name = name
        self.type = type
        self.lastMessage = lastMessage
        self.unreadCount = unreadCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case name
        case type
        case lastMessage
        case unreadCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(lastMessage, forKey: .lastMessage)
        try container.encodeIfPresent(unreadCount, forKey: .unreadCount)
    }
}

