//
// ChatEditMessage200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChatEditMessage200ResponseData: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var content: String?
    public var isE2ee: Bool?
    public var e2ee: AnyCodable?
    public var editedAt: String?

    public init(id: String? = nil, content: String? = nil, isE2ee: Bool? = nil, e2ee: AnyCodable? = nil, editedAt: String? = nil) {
        self.id = id
        self.content = content
        self.isE2ee = isE2ee
        self.e2ee = e2ee
        self.editedAt = editedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case content
        case isE2ee
        case e2ee
        case editedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encodeIfPresent(isE2ee, forKey: .isE2ee)
        try container.encodeIfPresent(e2ee, forKey: .e2ee)
        try container.encodeIfPresent(editedAt, forKey: .editedAt)
    }
}

