//
// ChatEditMessageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChatEditMessageRequest: Codable, JSONEncodable, Hashable {

    /** New plaintext (non-E2EE messages only). */
    public var content: String?
    public var e2ee: ChatEditMessageRequestE2ee?

    public init(content: String? = nil, e2ee: ChatEditMessageRequestE2ee? = nil) {
        self.content = content
        self.e2ee = e2ee
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case content
        case e2ee
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encodeIfPresent(e2ee, forKey: .e2ee)
    }
}

