//
// ComplianceLogSecurityEventRequestDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ComplianceLogSecurityEventRequestDetails: Codable, JSONEncodable, Hashable {

    public var userId: String?
    public var resource: String?
    public var ipAddress: String?
    public var userAgent: String?
    public var action: String?
    public var reason: String?

    public init(userId: String? = nil, resource: String? = nil, ipAddress: String? = nil, userAgent: String? = nil, action: String? = nil, reason: String? = nil) {
        self.userId = userId
        self.resource = resource
        self.ipAddress = ipAddress
        self.userAgent = userAgent
        self.action = action
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case resource
        case ipAddress
        case userAgent
        case action
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(resource, forKey: .resource)
        try container.encodeIfPresent(ipAddress, forKey: .ipAddress)
        try container.encodeIfPresent(userAgent, forKey: .userAgent)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(reason, forKey: .reason)
    }
}

