//
// ConfirmUploadResponseScan.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Virus scan result (provider, status, detections, raw analysis) */
public struct ConfirmUploadResponseScan: Codable, JSONEncodable, Hashable {

    public var status: String?
    public var provider: String?
    public var detections: Int?
    /** Raw analysis object returned by the scanner (e.g., VirusTotal) */
    public var analysis: AnyCodable?

    public init(status: String? = nil, provider: String? = nil, detections: Int? = nil, analysis: AnyCodable? = nil) {
        self.status = status
        self.provider = provider
        self.detections = detections
        self.analysis = analysis
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case provider
        case detections
        case analysis
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(detections, forKey: .detections)
        try container.encodeIfPresent(analysis, forKey: .analysis)
    }
}

