//
// CreateMonitoringAlertRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateMonitoringAlertRequest: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var condition: String?
    public var threshold: Double?
    public var action: String?
    public var projectId: String?

    public init(name: String? = nil, condition: String? = nil, threshold: Double? = nil, action: String? = nil, projectId: String? = nil) {
        self.name = name
        self.condition = condition
        self.threshold = threshold
        self.action = action
        self.projectId = projectId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case condition
        case threshold
        case action
        case projectId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(condition, forKey: .condition)
        try container.encodeIfPresent(threshold, forKey: .threshold)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(projectId, forKey: .projectId)
    }
}

