//
// CreateRoleRequestPermissionsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateRoleRequestPermissionsInner: Codable, JSONEncodable, Hashable {

    public enum Resource: String, Codable, CaseIterable {
        case project = "project"
        case collection = "collection"
        case data = "data"
        case file = "file"
        case apiKey = "api_key"
        case org = "org"
        case member = "member"
        case role = "role"
    }
    public enum Actions: String, Codable, CaseIterable {
        case create = "create"
        case read = "read"
        case update = "update"
        case delete = "delete"
        case manage = "manage"
    }
    public var resource: Resource?
    public var actions: [Actions]?
    public var conditions: AnyCodable?

    public init(resource: Resource? = nil, actions: [Actions]? = nil, conditions: AnyCodable? = nil) {
        self.resource = resource
        self.actions = actions
        self.conditions = conditions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resource
        case actions
        case conditions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(resource, forKey: .resource)
        try container.encodeIfPresent(actions, forKey: .actions)
        try container.encodeIfPresent(conditions, forKey: .conditions)
    }
}

