//
// CreateRoleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateRoleRequest: Codable, JSONEncodable, Hashable {

    public static let hierarchyRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public var name: String
    public var description: String?
    /** Legacy resource-level permissions. For data CRUD, prefer `collectionPermissions` below. */
    public var permissions: [CreateRoleRequestPermissionsInner]?
    public var hierarchy: Double?
    /** Per-collection CRUD map. Keys are collection slugs; value can be action array or object with actions + conditions. */
    public var collectionPermissions: [String: CreateRoleRequestCollectionPermissionsValue]?

    public init(name: String, description: String? = nil, permissions: [CreateRoleRequestPermissionsInner]? = nil, hierarchy: Double? = nil, collectionPermissions: [String: CreateRoleRequestCollectionPermissionsValue]? = nil) {
        self.name = name
        self.description = description
        self.permissions = permissions
        self.hierarchy = hierarchy
        self.collectionPermissions = collectionPermissions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case permissions
        case hierarchy
        case collectionPermissions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(permissions, forKey: .permissions)
        try container.encodeIfPresent(hierarchy, forKey: .hierarchy)
        try container.encodeIfPresent(collectionPermissions, forKey: .collectionPermissions)
    }
}

