//
// CreateOrganizationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateOrganizationRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    public var description: String?
    public var logo: String?
    public var website: String?
    public var parentOrgId: String?

    public init(name: String, description: String? = nil, logo: String? = nil, website: String? = nil, parentOrgId: String? = nil) {
        self.name = name
        self.description = description
        self.logo = logo
        self.website = website
        self.parentOrgId = parentOrgId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case logo
        case website
        case parentOrgId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(logo, forKey: .logo)
        try container.encodeIfPresent(website, forKey: .website)
        try container.encodeIfPresent(parentOrgId, forKey: .parentOrgId)
    }
}

