//
// CreateFunctionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload to create a function (name, description, code, trigger, environment). */
public struct CreateFunctionRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    public var description: String?
    /** Function body (async, has access to payload, db, files, messaging, wallet, utils, env, console) */
    public var code: String
    public var trigger: FunctionTrigger
    /** Per-function env vars injected into sandbox */
    public var environment: [String: String]?

    public init(name: String, description: String? = nil, code: String, trigger: FunctionTrigger, environment: [String: String]? = nil) {
        self.name = name
        self.description = description
        self.code = code
        self.trigger = trigger
        self.environment = environment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case code
        case trigger
        case environment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(code, forKey: .code)
        try container.encode(trigger, forKey: .trigger)
        try container.encodeIfPresent(environment, forKey: .environment)
    }
}

