//
// CreatePlan201Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreatePlan201Response: Codable, JSONEncodable, Hashable {

    public var message: String?
    public var plan: Plan?

    public init(message: String? = nil, plan: Plan? = nil) {
        self.message = message
        self.plan = plan
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case plan
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(plan, forKey: .plan)
    }
}

