//
// CreatePlanRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** OpenAPI-style body normalized server-side into Plan.pricing (monthly/yearly amounts), features (objects with name/included), and optional limits/trial/metadata. Slug is derived from projectId + name unless a collision occurs.  */
public struct CreatePlanRequest: Codable, JSONEncodable, Hashable {

    public enum Interval: String, Codable, CaseIterable {
        case month = "month"
        case year = "year"
    }
    /** Display name; also used to generate a unique slug per project. */
    public var name: String
    public var description: String?
    /** Amount for the chosen interval. The server fills the other billing period (e.g. yearly ≈ monthly × 12 × 0.8 when interval is month).  */
    public var price: Double
    /** ISO currency code (stored lowercased). */
    public var currency: String
    /** Which period `price` applies to; drives pricing.monthly vs pricing.yearly. */
    public var interval: Interval
    /** Strings become `{ name, included: true }`. You may send full feature objects instead.  */
    public var features: [CreatePlanRequestFeaturesInner]?
    public var limits: CreatePlanRequestLimits?
    public var trial: CreatePlanRequestTrial?
    public var isActive: Bool? = true
    /** Only one default plan per project is allowed server-side. */
    public var isDefault: Bool? = false
    /** Lower numbers list first in UIs. */
    public var sortOrder: Double?
    /** Arbitrary key/value data stored on the plan document. */
    public var metadata: [String: AnyCodable]?

    public init(name: String, description: String? = nil, price: Double, currency: String, interval: Interval, features: [CreatePlanRequestFeaturesInner]? = nil, limits: CreatePlanRequestLimits? = nil, trial: CreatePlanRequestTrial? = nil, isActive: Bool? = true, isDefault: Bool? = false, sortOrder: Double? = nil, metadata: [String: AnyCodable]? = nil) {
        self.name = name
        self.description = description
        self.price = price
        self.currency = currency
        self.interval = interval
        self.features = features
        self.limits = limits
        self.trial = trial
        self.isActive = isActive
        self.isDefault = isDefault
        self.sortOrder = sortOrder
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case price
        case currency
        case interval
        case features
        case limits
        case trial
        case isActive
        case isDefault
        case sortOrder
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(price, forKey: .price)
        try container.encode(currency, forKey: .currency)
        try container.encode(interval, forKey: .interval)
        try container.encodeIfPresent(features, forKey: .features)
        try container.encodeIfPresent(limits, forKey: .limits)
        try container.encodeIfPresent(trial, forKey: .trial)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(isDefault, forKey: .isDefault)
        try container.encodeIfPresent(sortOrder, forKey: .sortOrder)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

