//
// DashboardOverviewData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardOverviewData: Codable, JSONEncodable, Hashable {

    public var project: DashboardOverviewDataProject?
    public var requests: DashboardOverviewDataRequests?
    public var activeUsers: DashboardOverviewDataActiveUsers?
    public var latency: DashboardOverviewDataLatency?
    public var uptime: DashboardOverviewDataUptime?
    public var requestVolume14d: [DashboardOverviewDataRequestVolume14dInner]?
    public var recentActivity: [DashboardActivityItem]?
    public var generatedAt: Date?

    public init(project: DashboardOverviewDataProject? = nil, requests: DashboardOverviewDataRequests? = nil, activeUsers: DashboardOverviewDataActiveUsers? = nil, latency: DashboardOverviewDataLatency? = nil, uptime: DashboardOverviewDataUptime? = nil, requestVolume14d: [DashboardOverviewDataRequestVolume14dInner]? = nil, recentActivity: [DashboardActivityItem]? = nil, generatedAt: Date? = nil) {
        self.project = project
        self.requests = requests
        self.activeUsers = activeUsers
        self.latency = latency
        self.uptime = uptime
        self.requestVolume14d = requestVolume14d
        self.recentActivity = recentActivity
        self.generatedAt = generatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case project
        case requests
        case activeUsers
        case latency
        case uptime
        case requestVolume14d
        case recentActivity
        case generatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(project, forKey: .project)
        try container.encodeIfPresent(requests, forKey: .requests)
        try container.encodeIfPresent(activeUsers, forKey: .activeUsers)
        try container.encodeIfPresent(latency, forKey: .latency)
        try container.encodeIfPresent(uptime, forKey: .uptime)
        try container.encodeIfPresent(requestVolume14d, forKey: .requestVolume14d)
        try container.encodeIfPresent(recentActivity, forKey: .recentActivity)
        try container.encodeIfPresent(generatedAt, forKey: .generatedAt)
    }
}

