//
// DashboardActivityItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DashboardActivityItem: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var at: Date?
    public var action: String?
    public var title: String?
    public var detail: String?
    public var actorEmail: String?

    public init(id: String? = nil, at: Date? = nil, action: String? = nil, title: String? = nil, detail: String? = nil, actorEmail: String? = nil) {
        self.id = id
        self.at = at
        self.action = action
        self.title = title
        self.detail = detail
        self.actorEmail = actorEmail
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case at
        case action
        case title
        case detail
        case actorEmail
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(at, forKey: .at)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encodeIfPresent(actorEmail, forKey: .actorEmail)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension DashboardActivityItem: Identifiable {}
