//
// DatabaseConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Database configuration (collections list). */
public struct DatabaseConfig: Codable, JSONEncodable, Hashable {

    public var collections: [String]?

    public init(collections: [String]? = nil) {
        self.collections = collections
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collections
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(collections, forKey: .collections)
    }
}

