//
// DeviceRegisteredResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeviceRegisteredResponseData: Codable, JSONEncodable, Hashable {

    public enum Platform: String, Codable, CaseIterable {
        case ios = "ios"
        case android = "android"
        case web = "web"
        case unknown = "unknown"
    }
    public var token: String?
    public var platform: Platform?
    public var lastSeenAt: Date?

    public init(token: String? = nil, platform: Platform? = nil, lastSeenAt: Date? = nil) {
        self.token = token
        self.platform = platform
        self.lastSeenAt = lastSeenAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case platform
        case lastSeenAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(lastSeenAt, forKey: .lastSeenAt)
    }
}

