//
// EmailTemplateCatalogItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One row from GET /email/templates (full catalog for the project). */
public struct EmailTemplateCatalogItem: Codable, JSONEncodable, Hashable {

    public enum EffectiveSource: String, Codable, CaseIterable {
        case project = "project"
        case global = "global"
        case builtin = "builtin"
    }
    public var name: String?
    /** True if this project has a stored override for this template name. */
    public var isCustomized: Bool?
    /** Which layer is used at send time for this name. */
    public var effectiveSource: EffectiveSource?
    public var subjectSnippet: String?
    public var updatedAt: Date?
    public var version: Int?

    public init(name: String? = nil, isCustomized: Bool? = nil, effectiveSource: EffectiveSource? = nil, subjectSnippet: String? = nil, updatedAt: Date? = nil, version: Int? = nil) {
        self.name = name
        self.isCustomized = isCustomized
        self.effectiveSource = effectiveSource
        self.subjectSnippet = subjectSnippet
        self.updatedAt = updatedAt
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case isCustomized
        case effectiveSource
        case subjectSnippet
        case updatedAt
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(isCustomized, forKey: .isCustomized)
        try container.encodeIfPresent(effectiveSource, forKey: .effectiveSource)
        try container.encodeIfPresent(subjectSnippet, forKey: .subjectSnippet)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(version, forKey: .version)
    }
}

