//
// EnablePaymentProcessing200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EnablePaymentProcessing200ResponseData: Codable, JSONEncodable, Hashable {

    public var subaccountId: String?
    public var alreadyEnabled: Bool?

    public init(subaccountId: String? = nil, alreadyEnabled: Bool? = nil) {
        self.subaccountId = subaccountId
        self.alreadyEnabled = alreadyEnabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subaccountId
        case alreadyEnabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(subaccountId, forKey: .subaccountId)
        try container.encodeIfPresent(alreadyEnabled, forKey: .alreadyEnabled)
    }
}

