//
// FileUploadResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response after file upload (message, file metadata). */
public struct FileUploadResponse: Codable, JSONEncodable, Hashable {

    public var message: String?
    public var file: FileMetadata?

    public init(message: String? = nil, file: FileMetadata? = nil) {
        self.message = message
        self.file = file
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case file
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(file, forKey: .file)
    }
}

