//
// FunctionLogsResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FunctionLogsResponseData: Codable, JSONEncodable, Hashable {

    public var executions: [FunctionExecution]?
    public var stats: FunctionStats?

    public init(executions: [FunctionExecution]? = nil, stats: FunctionStats? = nil) {
        self.executions = executions
        self.stats = stats
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case executions
        case stats
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(executions, forKey: .executions)
        try container.encodeIfPresent(stats, forKey: .stats)
    }
}

