//
// GetComplianceSummary200ResponseComplianceSoc2.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetComplianceSummary200ResponseComplianceSoc2: Codable, JSONEncodable, Hashable {

    public var accessReviewsEnabled: Bool?
    public var auditLoggingEnabled: Bool?
    public var encryptionEnabled: Bool?

    public init(accessReviewsEnabled: Bool? = nil, auditLoggingEnabled: Bool? = nil, encryptionEnabled: Bool? = nil) {
        self.accessReviewsEnabled = accessReviewsEnabled
        self.auditLoggingEnabled = auditLoggingEnabled
        self.encryptionEnabled = encryptionEnabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessReviewsEnabled
        case auditLoggingEnabled
        case encryptionEnabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accessReviewsEnabled, forKey: .accessReviewsEnabled)
        try container.encodeIfPresent(auditLoggingEnabled, forKey: .auditLoggingEnabled)
        try container.encodeIfPresent(encryptionEnabled, forKey: .encryptionEnabled)
    }
}

