//
// GetCurrencyFeeBalance200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCurrencyFeeBalance200ResponseData: Codable, JSONEncodable, Hashable {

    public var currency: String?
    public var collectedAmount: Double?
    public var threshold: Double?
    public var status: String?

    public init(currency: String? = nil, collectedAmount: Double? = nil, threshold: Double? = nil, status: String? = nil) {
        self.currency = currency
        self.collectedAmount = collectedAmount
        self.threshold = threshold
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case collectedAmount
        case threshold
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(collectedAmount, forKey: .collectedAmount)
        try container.encodeIfPresent(threshold, forKey: .threshold)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

