//
// GetDashboard200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetDashboard200Response: Codable, JSONEncodable, Hashable {

    public var revenue: Double?
    public var subscriptions: Int?
    public var activePlans: Int?

    public init(revenue: Double? = nil, subscriptions: Int? = nil, activePlans: Int? = nil) {
        self.revenue = revenue
        self.subscriptions = subscriptions
        self.activePlans = activePlans
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case revenue
        case subscriptions
        case activePlans
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(revenue, forKey: .revenue)
        try container.encodeIfPresent(subscriptions, forKey: .subscriptions)
        try container.encodeIfPresent(activePlans, forKey: .activePlans)
    }
}

