//
// GetFeeBalances200ResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetFeeBalances200ResponseDataInner: Codable, JSONEncodable, Hashable {

    public var currency: String?
    public var collectedAmount: Double?
    public var threshold: Double?
    public var status: String?
    public var totalCollected: Double?
    public var totalPaidOut: Double?

    public init(currency: String? = nil, collectedAmount: Double? = nil, threshold: Double? = nil, status: String? = nil, totalCollected: Double? = nil, totalPaidOut: Double? = nil) {
        self.currency = currency
        self.collectedAmount = collectedAmount
        self.threshold = threshold
        self.status = status
        self.totalCollected = totalCollected
        self.totalPaidOut = totalPaidOut
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case collectedAmount
        case threshold
        case status
        case totalCollected
        case totalPaidOut
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(collectedAmount, forKey: .collectedAmount)
        try container.encodeIfPresent(threshold, forKey: .threshold)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(totalCollected, forKey: .totalCollected)
        try container.encodeIfPresent(totalPaidOut, forKey: .totalPaidOut)
    }
}

