//
// GetOrganizationUsers200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetOrganizationUsers200Response: Codable, JSONEncodable, Hashable {

    public var users: [GetOrganizationUsers200ResponseUsersInner]?
    public var total: Int?

    public init(users: [GetOrganizationUsers200ResponseUsersInner]? = nil, total: Int? = nil) {
        self.users = users
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case users
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(users, forKey: .users)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

