//
// GetOrganizationUsage200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetOrganizationUsage200Response: Codable, JSONEncodable, Hashable {

    public var usage: Usage?
    public var limits: Limits?
    public var plan: Plan?
    public var billing: Billing?
    public var suborgs: [GetOrganizationUsage200ResponseAllOfSuborgsInner]?

    public init(usage: Usage? = nil, limits: Limits? = nil, plan: Plan? = nil, billing: Billing? = nil, suborgs: [GetOrganizationUsage200ResponseAllOfSuborgsInner]? = nil) {
        self.usage = usage
        self.limits = limits
        self.plan = plan
        self.billing = billing
        self.suborgs = suborgs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case usage
        case limits
        case plan
        case billing
        case suborgs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(usage, forKey: .usage)
        try container.encodeIfPresent(limits, forKey: .limits)
        try container.encodeIfPresent(plan, forKey: .plan)
        try container.encodeIfPresent(billing, forKey: .billing)
        try container.encodeIfPresent(suborgs, forKey: .suborgs)
    }
}

