//
// GetPaymentRecords200ResponseDataPagination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPaymentRecords200ResponseDataPagination: Codable, JSONEncodable, Hashable {

    public var page: Int?
    public var limit: Int?
    public var total: Int?
    public var pages: Int?

    public init(page: Int? = nil, limit: Int? = nil, total: Int? = nil, pages: Int? = nil) {
        self.page = page
        self.limit = limit
        self.total = total
        self.pages = pages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case page
        case limit
        case total
        case pages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(pages, forKey: .pages)
    }
}

