//
// GetPaymentRecords200ResponseDataRecordsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPaymentRecords200ResponseDataRecordsInner: Codable, JSONEncodable, Hashable {

    public var txRef: String?
    public var amount: Double?
    public var orgReceives: Double?
    public var status: String?
    public var paidAt: String?

    public init(txRef: String? = nil, amount: Double? = nil, orgReceives: Double? = nil, status: String? = nil, paidAt: String? = nil) {
        self.txRef = txRef
        self.amount = amount
        self.orgReceives = orgReceives
        self.status = status
        self.paidAt = paidAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case txRef
        case amount
        case orgReceives
        case status
        case paidAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(txRef, forKey: .txRef)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(orgReceives, forKey: .orgReceives)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(paidAt, forKey: .paidAt)
    }
}

