//
// GetPayoutCountries200ResponseDataCountriesInnerFieldsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPayoutCountries200ResponseDataCountriesInnerFieldsInner: Codable, JSONEncodable, Hashable {

    public var key: String?
    public var label: String?
    public var type: String?
    public var _required: Bool?
    public var pattern: String?
    public var maxLength: Int?
    public var help: String?

    public init(key: String? = nil, label: String? = nil, type: String? = nil, _required: Bool? = nil, pattern: String? = nil, maxLength: Int? = nil, help: String? = nil) {
        self.key = key
        self.label = label
        self.type = type
        self._required = _required
        self.pattern = pattern
        self.maxLength = maxLength
        self.help = help
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case label
        case type
        case _required = "required"
        case pattern
        case maxLength
        case help
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(key, forKey: .key)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(_required, forKey: ._required)
        try container.encodeIfPresent(pattern, forKey: .pattern)
        try container.encodeIfPresent(maxLength, forKey: .maxLength)
        try container.encodeIfPresent(help, forKey: .help)
    }
}

