//
// GetScannerMetrics200ResponseAlertsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetScannerMetrics200ResponseAlertsInner: Codable, JSONEncodable, Hashable {

    public var chain: String?
    public var lag: Double?
    public var threshold: Double?

    public init(chain: String? = nil, lag: Double? = nil, threshold: Double? = nil) {
        self.chain = chain
        self.lag = lag
        self.threshold = threshold
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chain
        case lag
        case threshold
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(chain, forKey: .chain)
        try container.encodeIfPresent(lag, forKey: .lag)
        try container.encodeIfPresent(threshold, forKey: .threshold)
    }
}

