//
// GetUserOverview200ResponseFootprint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetUserOverview200ResponseFootprint: Codable, JSONEncodable, Hashable {

    public var fileCount: Int?
    public var storageUsed: Int?
    public var sessionCount: Int?
    public var apiKeyCount: Int?
    public var collectionsInProject: Int?
    public var collections: [GetOrganizationUsers200ResponseUsersInnerProject]?

    public init(fileCount: Int? = nil, storageUsed: Int? = nil, sessionCount: Int? = nil, apiKeyCount: Int? = nil, collectionsInProject: Int? = nil, collections: [GetOrganizationUsers200ResponseUsersInnerProject]? = nil) {
        self.fileCount = fileCount
        self.storageUsed = storageUsed
        self.sessionCount = sessionCount
        self.apiKeyCount = apiKeyCount
        self.collectionsInProject = collectionsInProject
        self.collections = collections
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fileCount
        case storageUsed
        case sessionCount
        case apiKeyCount
        case collectionsInProject
        case collections
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fileCount, forKey: .fileCount)
        try container.encodeIfPresent(storageUsed, forKey: .storageUsed)
        try container.encodeIfPresent(sessionCount, forKey: .sessionCount)
        try container.encodeIfPresent(apiKeyCount, forKey: .apiKeyCount)
        try container.encodeIfPresent(collectionsInProject, forKey: .collectionsInProject)
        try container.encodeIfPresent(collections, forKey: .collections)
    }
}

