//
// HealthResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Health check response (status, timestamp, services, version, uptime). */
public struct HealthResponse: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case healthy = "healthy"
        case unhealthy = "unhealthy"
    }
    public var status: Status?
    public var timestamp: Date?
    public var services: HealthResponseServices?
    public var version: String?
    public var uptime: Int?

    public init(status: Status? = nil, timestamp: Date? = nil, services: HealthResponseServices? = nil, version: String? = nil, uptime: Int? = nil) {
        self.status = status
        self.timestamp = timestamp
        self.services = services
        self.version = version
        self.uptime = uptime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case timestamp
        case services
        case version
        case uptime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(services, forKey: .services)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(uptime, forKey: .uptime)
    }
}

