//
// InitializePaymentForProjectRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InitializePaymentForProjectRequest: Codable, JSONEncodable, Hashable {

    public static let amountRule = NumericRule<Double>(minimum: 0.01, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var amount: Double
    public var currency: String? = "USD"
    public var customer: InitializePaymentRequestCustomer
    public var metadata: AnyCodable?

    public init(amount: Double, currency: String? = "USD", customer: InitializePaymentRequestCustomer, metadata: AnyCodable? = nil) {
        self.amount = amount
        self.currency = currency
        self.customer = customer
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case currency
        case customer
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encode(customer, forKey: .customer)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

