//
// IntegrationsExecuteRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IntegrationsExecuteRequest: Codable, JSONEncodable, Hashable {

    public enum Method: String, Codable, CaseIterable {
        case _get = "GET"
        case post = "POST"
        case put = "PUT"
        case patch = "PATCH"
        case delete = "DELETE"
    }
    public var endpoint: String
    public var method: Method
    public var params: AnyCodable?
    public var body: AnyCodable?

    public init(endpoint: String, method: Method, params: AnyCodable? = nil, body: AnyCodable? = nil) {
        self.endpoint = endpoint
        self.method = method
        self.params = params
        self.body = body
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpoint
        case method
        case params
        case body
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(endpoint, forKey: .endpoint)
        try container.encode(method, forKey: .method)
        try container.encodeIfPresent(params, forKey: .params)
        try container.encodeIfPresent(body, forKey: .body)
    }
}

