//
// ListBackups200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListBackups200Response: Codable, JSONEncodable, Hashable {

    public var backups: [ListBackups200ResponseBackupsInner]?
    public var total: Int?

    public init(backups: [ListBackups200ResponseBackupsInner]? = nil, total: Int? = nil) {
        self.backups = backups
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case backups
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(backups, forKey: .backups)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

