//
// MagicLinkRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Email and projectId to send a passwordless magic link; optional redirectUrl. */
public struct MagicLinkRequest: Codable, JSONEncodable, Hashable {

    public var email: String
    public var projectId: String
    public var redirectUrl: String?

    public init(email: String, projectId: String, redirectUrl: String? = nil) {
        self.email = email
        self.projectId = projectId
        self.redirectUrl = redirectUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case projectId
        case redirectUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(projectId, forKey: .projectId)
        try container.encodeIfPresent(redirectUrl, forKey: .redirectUrl)
    }
}

