//
// MonitoringAnalyticsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MonitoringAnalyticsResponse: Codable, JSONEncodable, Hashable {

    public var period: String?
    public var granularity: String?
    /** Present when rolling window used */
    public var days: Int?
    public var stats: [MonitoringAnalyticsResponseStatsInner]?
    public var totals: MonitoringAnalyticsResponseTotals?

    public init(period: String? = nil, granularity: String? = nil, days: Int? = nil, stats: [MonitoringAnalyticsResponseStatsInner]? = nil, totals: MonitoringAnalyticsResponseTotals? = nil) {
        self.period = period
        self.granularity = granularity
        self.days = days
        self.stats = stats
        self.totals = totals
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case period
        case granularity
        case days
        case stats
        case totals
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(period, forKey: .period)
        try container.encodeIfPresent(granularity, forKey: .granularity)
        try container.encodeIfPresent(days, forKey: .days)
        try container.encodeIfPresent(stats, forKey: .stats)
        try container.encodeIfPresent(totals, forKey: .totals)
    }
}

