//
// MonitoringAnalyticsResponseStatsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MonitoringAnalyticsResponseStatsInner: Codable, JSONEncodable, Hashable {

    public var date: String?
    public var apiCalls: Int?
    public var dbReads: Int?
    public var dbWrites: Int?
    public var storage: Int?
    public var bandwidth: Int?

    public init(date: String? = nil, apiCalls: Int? = nil, dbReads: Int? = nil, dbWrites: Int? = nil, storage: Int? = nil, bandwidth: Int? = nil) {
        self.date = date
        self.apiCalls = apiCalls
        self.dbReads = dbReads
        self.dbWrites = dbWrites
        self.storage = storage
        self.bandwidth = bandwidth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case apiCalls
        case dbReads
        case dbWrites
        case storage
        case bandwidth
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(apiCalls, forKey: .apiCalls)
        try container.encodeIfPresent(dbReads, forKey: .dbReads)
        try container.encodeIfPresent(dbWrites, forKey: .dbWrites)
        try container.encodeIfPresent(storage, forKey: .storage)
        try container.encodeIfPresent(bandwidth, forKey: .bandwidth)
    }
}

