//
// OrgDomainEntryWithDns.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Full allowed-domain row (admin and legacy): includes **&#x60;dnsTxtHost&#x60;** / **&#x60;dnsTxtValue&#x60;**, optional managed edge TLS hints, staff-published step-3 TXT (&#x60;platformDnsVerification&#x60; on the manual path), and unified **&#x60;dnsRecords&#x60;** when the API builds a checklist. **&#x60;routingCnameTarget&#x60;** is the managed routing CNAME target when the certificate has provisioned, else the platform default. Org-facing routes return the compact **&#x60;OrgDomainEntryOrgConsole&#x60;** shape instead (no raw &#x60;verificationToken&#x60; or duplicate TXT keys). */
public struct OrgDomainEntryWithDns: Codable, JSONEncodable, Hashable {

    public enum Source: String, Codable, CaseIterable {
        case manual = "manual"
        case api = "api"
        case imported = "imported"
    }
    /** Subdocument id when present (MongoDB) */
    public var id: String?
    public var hostname: String?
    public var hostnameNormalized: String?
    public var status: String?
    public var isPrimary: Bool?
    public var source: Source?
    public var verificationToken: String?
    public var createdAt: Date?
    public var verifiedAt: Date?
    public var lastVerifiedAt: Date?
    /** FQDN for the TXT record (e.g. _mudbase-verify.example.com) */
    public var dnsTxtHost: String?
    /** Exact TXT string value (mudbase-domain-verification=<token>) */
    public var dnsTxtValue: String?
    public var edge: OrgEdgeHints?
    /** True while Mudbase TXT passed but custom host not yet active (includes CNAME and platform DNS pipeline). */
    public var platformActivationPending: Bool?
    public var customDomainLiveForApiTraffic: Bool?
    /** Console wizard step 1–3; null when active/verified. */
    public var customDomainVerificationStep: Int?
    /** Routing CNAME target: the managed certificate's provisioned CNAME target when requirements have been stored; otherwise the platform default target. */
    public var routingCnameTarget: String?
    /** Unified checklist: Mudbase ownership TXT, routing CNAME (purpose `routing`) when provisioned else the platform default, and the managed certificate-provisioning rows once the managed certificate has been provisioned after the Mudbase TXT. Empty or absent when the certificate is not yet provisioned. Prefer this over `platformDnsVerification` alone for org-facing DNS UI. */
    public var dnsRecords: [OrgDnsRecord]?
    /** Managed certificate `status` during provisioning (e.g. `pending_validation`, `active`). Null when managed certificate provisioning is not in use for this deployment. */
    public var flyCertificateStatus: String?
    public var platformDnsVerification: OrgPlatformDnsVerificationCustomer?
    public var cnameSubmittedAt: Date?
    public var cnameApprovedAt: Date?
    public var platformDnsVerificationSubmittedAt: Date?

    public init(id: String? = nil, hostname: String? = nil, hostnameNormalized: String? = nil, status: String? = nil, isPrimary: Bool? = nil, source: Source? = nil, verificationToken: String? = nil, createdAt: Date? = nil, verifiedAt: Date? = nil, lastVerifiedAt: Date? = nil, dnsTxtHost: String? = nil, dnsTxtValue: String? = nil, edge: OrgEdgeHints? = nil, platformActivationPending: Bool? = nil, customDomainLiveForApiTraffic: Bool? = nil, customDomainVerificationStep: Int? = nil, routingCnameTarget: String? = nil, dnsRecords: [OrgDnsRecord]? = nil, flyCertificateStatus: String? = nil, platformDnsVerification: OrgPlatformDnsVerificationCustomer? = nil, cnameSubmittedAt: Date? = nil, cnameApprovedAt: Date? = nil, platformDnsVerificationSubmittedAt: Date? = nil) {
        self.id = id
        self.hostname = hostname
        self.hostnameNormalized = hostnameNormalized
        self.status = status
        self.isPrimary = isPrimary
        self.source = source
        self.verificationToken = verificationToken
        self.createdAt = createdAt
        self.verifiedAt = verifiedAt
        self.lastVerifiedAt = lastVerifiedAt
        self.dnsTxtHost = dnsTxtHost
        self.dnsTxtValue = dnsTxtValue
        self.edge = edge
        self.platformActivationPending = platformActivationPending
        self.customDomainLiveForApiTraffic = customDomainLiveForApiTraffic
        self.customDomainVerificationStep = customDomainVerificationStep
        self.routingCnameTarget = routingCnameTarget
        self.dnsRecords = dnsRecords
        self.flyCertificateStatus = flyCertificateStatus
        self.platformDnsVerification = platformDnsVerification
        self.cnameSubmittedAt = cnameSubmittedAt
        self.cnameApprovedAt = cnameApprovedAt
        self.platformDnsVerificationSubmittedAt = platformDnsVerificationSubmittedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case hostname
        case hostnameNormalized
        case status
        case isPrimary
        case source
        case verificationToken
        case createdAt
        case verifiedAt
        case lastVerifiedAt
        case dnsTxtHost
        case dnsTxtValue
        case edge
        case platformActivationPending
        case customDomainLiveForApiTraffic
        case customDomainVerificationStep
        case routingCnameTarget
        case dnsRecords
        case flyCertificateStatus
        case platformDnsVerification
        case cnameSubmittedAt
        case cnameApprovedAt
        case platformDnsVerificationSubmittedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(hostname, forKey: .hostname)
        try container.encodeIfPresent(hostnameNormalized, forKey: .hostnameNormalized)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(isPrimary, forKey: .isPrimary)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(verificationToken, forKey: .verificationToken)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(verifiedAt, forKey: .verifiedAt)
        try container.encodeIfPresent(lastVerifiedAt, forKey: .lastVerifiedAt)
        try container.encodeIfPresent(dnsTxtHost, forKey: .dnsTxtHost)
        try container.encodeIfPresent(dnsTxtValue, forKey: .dnsTxtValue)
        try container.encodeIfPresent(edge, forKey: .edge)
        try container.encodeIfPresent(platformActivationPending, forKey: .platformActivationPending)
        try container.encodeIfPresent(customDomainLiveForApiTraffic, forKey: .customDomainLiveForApiTraffic)
        try container.encodeIfPresent(customDomainVerificationStep, forKey: .customDomainVerificationStep)
        try container.encodeIfPresent(routingCnameTarget, forKey: .routingCnameTarget)
        try container.encodeIfPresent(dnsRecords, forKey: .dnsRecords)
        try container.encodeIfPresent(flyCertificateStatus, forKey: .flyCertificateStatus)
        try container.encodeIfPresent(platformDnsVerification, forKey: .platformDnsVerification)
        try container.encodeIfPresent(cnameSubmittedAt, forKey: .cnameSubmittedAt)
        try container.encodeIfPresent(cnameApprovedAt, forKey: .cnameApprovedAt)
        try container.encodeIfPresent(platformDnsVerificationSubmittedAt, forKey: .platformDnsVerificationSubmittedAt)
    }
}

