//
// OrgDomainEntryOrgConsole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Org API compact domain row: use **&#x60;dnsRecords&#x60;** for the Mudbase ownership TXT (purpose &#x60;mudbase_ownership&#x60;) and routing CNAME. Omits &#x60;hostnameNormalized&#x60;, &#x60;verificationToken&#x60;, &#x60;dnsTxtHost&#x60;, and &#x60;dnsTxtValue&#x60;. Omits &#x60;cloudflareEdge&#x60; when Cloudflare SaaS is not configured. Optional keys with no value are omitted from JSON responses. */
public struct OrgDomainEntryOrgConsole: Codable, JSONEncodable, Hashable {

    public enum Source: String, Codable, CaseIterable {
        case manual = "manual"
        case api = "api"
        case imported = "imported"
    }
    public var id: String?
    public var hostname: String?
    public var status: String?
    public var isPrimary: Bool?
    public var source: Source?
    public var createdAt: Date?
    public var verifiedAt: Date?
    public var lastVerifiedAt: Date?
    public var cnameSubmittedAt: Date?
    public var cnameApprovedAt: Date?
    public var customDomainVerificationStep: Int?
    public var routingCnameTarget: String?
    public var dnsRecords: [OrgDnsRecord]?
    public var platformActivationPending: Bool?
    public var customDomainLiveForApiTraffic: Bool?
    public var cloudflareEdge: OrgCloudflareEdgeHints?
    public var flyCertificateStatus: String?
    public var platformDnsVerification: OrgPlatformDnsVerificationCustomer?
    public var platformDnsVerificationSubmittedAt: Date?

    public init(id: String? = nil, hostname: String? = nil, status: String? = nil, isPrimary: Bool? = nil, source: Source? = nil, createdAt: Date? = nil, verifiedAt: Date? = nil, lastVerifiedAt: Date? = nil, cnameSubmittedAt: Date? = nil, cnameApprovedAt: Date? = nil, customDomainVerificationStep: Int? = nil, routingCnameTarget: String? = nil, dnsRecords: [OrgDnsRecord]? = nil, platformActivationPending: Bool? = nil, customDomainLiveForApiTraffic: Bool? = nil, cloudflareEdge: OrgCloudflareEdgeHints? = nil, flyCertificateStatus: String? = nil, platformDnsVerification: OrgPlatformDnsVerificationCustomer? = nil, platformDnsVerificationSubmittedAt: Date? = nil) {
        self.id = id
        self.hostname = hostname
        self.status = status
        self.isPrimary = isPrimary
        self.source = source
        self.createdAt = createdAt
        self.verifiedAt = verifiedAt
        self.lastVerifiedAt = lastVerifiedAt
        self.cnameSubmittedAt = cnameSubmittedAt
        self.cnameApprovedAt = cnameApprovedAt
        self.customDomainVerificationStep = customDomainVerificationStep
        self.routingCnameTarget = routingCnameTarget
        self.dnsRecords = dnsRecords
        self.platformActivationPending = platformActivationPending
        self.customDomainLiveForApiTraffic = customDomainLiveForApiTraffic
        self.cloudflareEdge = cloudflareEdge
        self.flyCertificateStatus = flyCertificateStatus
        self.platformDnsVerification = platformDnsVerification
        self.platformDnsVerificationSubmittedAt = platformDnsVerificationSubmittedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case hostname
        case status
        case isPrimary
        case source
        case createdAt
        case verifiedAt
        case lastVerifiedAt
        case cnameSubmittedAt
        case cnameApprovedAt
        case customDomainVerificationStep
        case routingCnameTarget
        case dnsRecords
        case platformActivationPending
        case customDomainLiveForApiTraffic
        case cloudflareEdge
        case flyCertificateStatus
        case platformDnsVerification
        case platformDnsVerificationSubmittedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(hostname, forKey: .hostname)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(isPrimary, forKey: .isPrimary)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(verifiedAt, forKey: .verifiedAt)
        try container.encodeIfPresent(lastVerifiedAt, forKey: .lastVerifiedAt)
        try container.encodeIfPresent(cnameSubmittedAt, forKey: .cnameSubmittedAt)
        try container.encodeIfPresent(cnameApprovedAt, forKey: .cnameApprovedAt)
        try container.encodeIfPresent(customDomainVerificationStep, forKey: .customDomainVerificationStep)
        try container.encodeIfPresent(routingCnameTarget, forKey: .routingCnameTarget)
        try container.encodeIfPresent(dnsRecords, forKey: .dnsRecords)
        try container.encodeIfPresent(platformActivationPending, forKey: .platformActivationPending)
        try container.encodeIfPresent(customDomainLiveForApiTraffic, forKey: .customDomainLiveForApiTraffic)
        try container.encodeIfPresent(cloudflareEdge, forKey: .cloudflareEdge)
        try container.encodeIfPresent(flyCertificateStatus, forKey: .flyCertificateStatus)
        try container.encodeIfPresent(platformDnsVerification, forKey: .platformDnsVerification)
        try container.encodeIfPresent(platformDnsVerificationSubmittedAt, forKey: .platformDnsVerificationSubmittedAt)
    }
}

