//
// OTPVerifyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** OTP code and identifier (phone/email) for verification. */
public struct OTPVerifyRequest: Codable, JSONEncodable, Hashable {

    public var identifier: String?
    public var otp: String
    public var projectId: String

    public init(identifier: String? = nil, otp: String, projectId: String) {
        self.identifier = identifier
        self.otp = otp
        self.projectId = projectId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identifier
        case otp
        case projectId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(identifier, forKey: .identifier)
        try container.encode(otp, forKey: .otp)
        try container.encode(projectId, forKey: .projectId)
    }
}

