//
// Plan.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Subscription plan (name, price, currency, interval, features). */
public struct Plan: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var price: Double?
    public var currency: String?
    public var interval: String?
    public var features: [String]?

    public init(name: String? = nil, price: Double? = nil, currency: String? = nil, interval: String? = nil, features: [String]? = nil) {
        self.name = name
        self.price = price
        self.currency = currency
        self.interval = interval
        self.features = features
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case price
        case currency
        case interval
        case features
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(interval, forKey: .interval)
        try container.encodeIfPresent(features, forKey: .features)
    }
}

