//
// ProvisionEnterpriseRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProvisionEnterpriseRequest: Codable, JSONEncodable, Hashable {

    public var orgId: String
    public var provisionRequestId: String
    public var apiBaseUrl: String
    public var dbRef: String
    public var serverId: String
    public var region: String?
    public var version: String?
    public var forceOverride: Bool?

    public init(orgId: String, provisionRequestId: String, apiBaseUrl: String, dbRef: String, serverId: String, region: String? = nil, version: String? = nil, forceOverride: Bool? = nil) {
        self.orgId = orgId
        self.provisionRequestId = provisionRequestId
        self.apiBaseUrl = apiBaseUrl
        self.dbRef = dbRef
        self.serverId = serverId
        self.region = region
        self.version = version
        self.forceOverride = forceOverride
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orgId
        case provisionRequestId
        case apiBaseUrl
        case dbRef
        case serverId
        case region
        case version
        case forceOverride
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(orgId, forKey: .orgId)
        try container.encode(provisionRequestId, forKey: .provisionRequestId)
        try container.encode(apiBaseUrl, forKey: .apiBaseUrl)
        try container.encode(dbRef, forKey: .dbRef)
        try container.encode(serverId, forKey: .serverId)
        try container.encodeIfPresent(region, forKey: .region)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(forceOverride, forKey: .forceOverride)
    }
}

