//
// PushNotificationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Provide at least one target: &#x60;tokens&#x60; (registered device tokens), &#x60;endpoints&#x60; (registered Web Push subscription endpoints), &#x60;userIds&#x60; (Web Push subscriptions associated to those user ids), or &#x60;webPushBroadcast: true&#x60; (every enabled Web Push subscription in the project). A single send can target both the device-token channel and the native Web Push channel at once.  */
public struct PushNotificationRequest: Codable, JSONEncodable, Hashable {

    /** Registered device push tokens to deliver to (device-token channel). */
    public var tokens: [String]?
    /** Registered Web Push subscription endpoints to deliver to (native Web Push channel).  */
    public var endpoints: [String]?
    /** Deliver to every Web Push subscription registered under these user ids (native Web Push channel).  */
    public var userIds: [String]?
    /** When true, deliver to every enabled Web Push subscription registered to the project (native Web Push channel). Ignored when the project has not enabled native Web Push.  */
    public var webPushBroadcast: Bool?
    public var title: String
    public var body: String
    public var data: AnyCodable?
    public var imageUrl: String?

    public init(tokens: [String]? = nil, endpoints: [String]? = nil, userIds: [String]? = nil, webPushBroadcast: Bool? = nil, title: String, body: String, data: AnyCodable? = nil, imageUrl: String? = nil) {
        self.tokens = tokens
        self.endpoints = endpoints
        self.userIds = userIds
        self.webPushBroadcast = webPushBroadcast
        self.title = title
        self.body = body
        self.data = data
        self.imageUrl = imageUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokens
        case endpoints
        case userIds
        case webPushBroadcast
        case title
        case body
        case data
        case imageUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tokens, forKey: .tokens)
        try container.encodeIfPresent(endpoints, forKey: .endpoints)
        try container.encodeIfPresent(userIds, forKey: .userIds)
        try container.encodeIfPresent(webPushBroadcast, forKey: .webPushBroadcast)
        try container.encode(title, forKey: .title)
        try container.encode(body, forKey: .body)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
    }
}

