//
// RealtimeAnalyticsGetActiveUsers200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RealtimeAnalyticsGetActiveUsers200Response: Codable, JSONEncodable, Hashable {

    public var users: [RealtimeAnalyticsGetActiveUsers200ResponseUsersInner]?
    public var count: Int?
    public var timestamp: Date?

    public init(users: [RealtimeAnalyticsGetActiveUsers200ResponseUsersInner]? = nil, count: Int? = nil, timestamp: Date? = nil) {
        self.users = users
        self.count = count
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case users
        case count
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(users, forKey: .users)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
    }
}

