//
// RegisterWithRole201Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegisterWithRole201Response: Codable, JSONEncodable, Hashable {

    public var message: String?
    /** True when the project requires email verification before a session is issued - no token is returned in that case. */
    public var requireVerification: Bool?
    /** JWT access token. Absent when requireVerification is true. */
    public var token: String?
    /** JWT refresh token. Absent when requireVerification is true. */
    public var refreshToken: String?
    /** Access token TTL in seconds. Absent when requireVerification is true. */
    public var expiresIn: Int?
    public var user: RegisterWithRole201ResponseUser?
    public var role: RegisterWithRole201ResponseRole?

    public init(message: String? = nil, requireVerification: Bool? = nil, token: String? = nil, refreshToken: String? = nil, expiresIn: Int? = nil, user: RegisterWithRole201ResponseUser? = nil, role: RegisterWithRole201ResponseRole? = nil) {
        self.message = message
        self.requireVerification = requireVerification
        self.token = token
        self.refreshToken = refreshToken
        self.expiresIn = expiresIn
        self.user = user
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case requireVerification
        case token
        case refreshToken
        case expiresIn
        case user
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(requireVerification, forKey: .requireVerification)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(refreshToken, forKey: .refreshToken)
        try container.encodeIfPresent(expiresIn, forKey: .expiresIn)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(role, forKey: .role)
    }
}

