//
// RoleElevationUploadDocumentsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RoleElevationUploadDocumentsRequest: Codable, JSONEncodable, Hashable {

    public var roleSlug: String
    public var documents: [RoleElevationUploadDocumentsRequestDocumentsInner]

    public init(roleSlug: String, documents: [RoleElevationUploadDocumentsRequestDocumentsInner]) {
        self.roleSlug = roleSlug
        self.documents = documents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case roleSlug
        case documents
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(roleSlug, forKey: .roleSlug)
        try container.encode(documents, forKey: .documents)
    }
}

