//
// SearchGetAnalytics200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchGetAnalytics200Response: Codable, JSONEncodable, Hashable {

    public var totalSearches: Int?
    public var topQueries: [SearchGetAnalytics200ResponseTopQueriesInner]?
    public var searchesByCollection: AnyCodable?
    public var averageResponseTime: Double?

    public init(totalSearches: Int? = nil, topQueries: [SearchGetAnalytics200ResponseTopQueriesInner]? = nil, searchesByCollection: AnyCodable? = nil, averageResponseTime: Double? = nil) {
        self.totalSearches = totalSearches
        self.topQueries = topQueries
        self.searchesByCollection = searchesByCollection
        self.averageResponseTime = averageResponseTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalSearches
        case topQueries
        case searchesByCollection
        case averageResponseTime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalSearches, forKey: .totalSearches)
        try container.encodeIfPresent(topQueries, forKey: .topQueries)
        try container.encodeIfPresent(searchesByCollection, forKey: .searchesByCollection)
        try container.encodeIfPresent(averageResponseTime, forKey: .averageResponseTime)
    }
}

