//
// SendPushNotification429Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendPushNotification429Response: Codable, JSONEncodable, Hashable {

    public var success: Bool?
    public var error: String?
    public var message: String?

    public init(success: Bool? = nil, error: String? = nil, message: String? = nil) {
        self.success = success
        self.error = error
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case error
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

