//
// SessionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Current session with user and authenticated flag. */
public struct SessionResponse: Codable, JSONEncodable, Hashable {

    public var user: User?
    public var authenticated: Bool?

    public init(user: User? = nil, authenticated: Bool? = nil) {
        self.user = user
        self.authenticated = authenticated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case authenticated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(authenticated, forKey: .authenticated)
    }
}

