//
// SimulateAppPermissions200ResponseEvaluated.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SimulateAppPermissions200ResponseEvaluated: Codable, JSONEncodable, Hashable {

    public var role: String?
    public var method: String?
    public var pathname: String?
    public var operationId: String?
    public var resource: String?
    public var action: String?

    public init(role: String? = nil, method: String? = nil, pathname: String? = nil, operationId: String? = nil, resource: String? = nil, action: String? = nil) {
        self.role = role
        self.method = method
        self.pathname = pathname
        self.operationId = operationId
        self.resource = resource
        self.action = action
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case role
        case method
        case pathname
        case operationId
        case resource
        case action
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(method, forKey: .method)
        try container.encodeIfPresent(pathname, forKey: .pathname)
        try container.encodeIfPresent(operationId, forKey: .operationId)
        try container.encodeIfPresent(resource, forKey: .resource)
        try container.encodeIfPresent(action, forKey: .action)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        role = try container.decodeIfPresent(String.self, forKey: .role)
        method = try container.decodeIfPresent(String.self, forKey: .method)
        pathname = try container.decodeIfPresent(String.self, forKey: .pathname)
        operationId = try container.decodeIfPresent(String.self, forKey: .operationId)
        resource = try container.decodeIfPresent(String.self, forKey: .resource)
        action = try container.decodeIfPresent(String.self, forKey: .action)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("role")
        nonAdditionalPropertyKeys.insert("method")
        nonAdditionalPropertyKeys.insert("pathname")
        nonAdditionalPropertyKeys.insert("operationId")
        nonAdditionalPropertyKeys.insert("resource")
        nonAdditionalPropertyKeys.insert("action")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(AnyCodable.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}

