//
// StorageGetPresignedUploadRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StorageGetPresignedUploadRequest: Codable, JSONEncodable, Hashable {

    public var projectId: String
    public var bucket: String? = "default"
    public var originalName: String
    public var contentType: String?
    public var isPublic: Bool? = false

    public init(projectId: String, bucket: String? = "default", originalName: String, contentType: String? = nil, isPublic: Bool? = false) {
        self.projectId = projectId
        self.bucket = bucket
        self.originalName = originalName
        self.contentType = contentType
        self.isPublic = isPublic
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId
        case bucket
        case originalName
        case contentType
        case isPublic
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(projectId, forKey: .projectId)
        try container.encodeIfPresent(bucket, forKey: .bucket)
        try container.encode(originalName, forKey: .originalName)
        try container.encodeIfPresent(contentType, forKey: .contentType)
        try container.encodeIfPresent(isPublic, forKey: .isPublic)
    }
}

