//
// SystemStatusResponseDataRequests.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SystemStatusResponseDataRequests: Codable, JSONEncodable, Hashable {

    public var total: Int?
    public var successful: Int?
    public var errors: Int?
    public var errorRate: Double?

    public init(total: Int? = nil, successful: Int? = nil, errors: Int? = nil, errorRate: Double? = nil) {
        self.total = total
        self.successful = successful
        self.errors = errors
        self.errorRate = errorRate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case successful
        case errors
        case errorRate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(successful, forKey: .successful)
        try container.encodeIfPresent(errors, forKey: .errors)
        try container.encodeIfPresent(errorRate, forKey: .errorRate)
    }
}

