//
// TestWebhookTransformation200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestWebhookTransformation200ResponseData: Codable, JSONEncodable, Hashable {

    public var original: AnyCodable?
    public var transformed: AnyCodable?

    public init(original: AnyCodable? = nil, transformed: AnyCodable? = nil) {
        self.original = original
        self.transformed = transformed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case original
        case transformed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(original, forKey: .original)
        try container.encodeIfPresent(transformed, forKey: .transformed)
    }
}

