//
// TriggerWebhookResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TriggerWebhookResponse: Codable, JSONEncodable, Hashable {

    public var message: String
    /** WebhookLog._id for this delivery; use in POST /api/webhooks/retry/{webhookId} */
    public var webhookId: String

    public init(message: String, webhookId: String) {
        self.message = message
        self.webhookId = webhookId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case webhookId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(webhookId, forKey: .webhookId)
    }
}

