//
// UpdateProjectRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Fields to update on a project (name, description, logoUrl, settings, auth). */
public struct UpdateProjectRequest: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var description: String?
    /** Public URL for the project logo/brand image. Prefer uploading via **POST /api/projects/{id}/logo** or **POST /api/projects/{orgId}/projects/{id}/logo** (stored under logo/project/ in platform storage). Used in project-related emails.  */
    public var logoUrl: String?
    public var settings: ProjectSettings?
    public var auth: AuthConfig?

    public init(name: String? = nil, description: String? = nil, logoUrl: String? = nil, settings: ProjectSettings? = nil, auth: AuthConfig? = nil) {
        self.name = name
        self.description = description
        self.logoUrl = logoUrl
        self.settings = settings
        self.auth = auth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case logoUrl
        case settings
        case auth
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(logoUrl, forKey: .logoUrl)
        try container.encodeIfPresent(settings, forKey: .settings)
        try container.encodeIfPresent(auth, forKey: .auth)
    }
}

