//
// UpdateCurrencyFeeSettingsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateCurrencyFeeSettingsRequest: Codable, JSONEncodable, Hashable {

    public var enabled: Bool?
    public var feeAmount: Double?
    public var payoutAddress: String?
    public var payoutThreshold: Double?

    public init(enabled: Bool? = nil, feeAmount: Double? = nil, payoutAddress: String? = nil, payoutThreshold: Double? = nil) {
        self.enabled = enabled
        self.feeAmount = feeAmount
        self.payoutAddress = payoutAddress
        self.payoutThreshold = payoutThreshold
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case feeAmount
        case payoutAddress
        case payoutThreshold
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(feeAmount, forKey: .feeAmount)
        try container.encodeIfPresent(payoutAddress, forKey: .payoutAddress)
        try container.encodeIfPresent(payoutThreshold, forKey: .payoutThreshold)
    }
}

