//
// UpdateOrganization200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateOrganization200Response: Codable, JSONEncodable, Hashable {

    public var message: String?
    public var org: Organization?

    public init(message: String? = nil, org: Organization? = nil) {
        self.message = message
        self.org = org
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case org
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(org, forKey: .org)
    }
}

