//
// UpdateApiKey200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateApiKey200Response: Codable, JSONEncodable, Hashable {

    public var message: String?
    public var apiKey: ApiKey?

    public init(message: String? = nil, apiKey: ApiKey? = nil) {
        self.message = message
        self.apiKey = apiKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case apiKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(apiKey, forKey: .apiKey)
    }
}

