//
// UploadFilesToBucketMetadataRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Optional metadata for file upload (folder, tags). Use with application/json when not sending binary files. */
public struct UploadFilesToBucketMetadataRequest: Codable, JSONEncodable, Hashable {

    public var folder: String?
    public var tags: [String]?

    public init(folder: String? = nil, tags: [String]? = nil) {
        self.folder = folder
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case folder
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(folder, forKey: .folder)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

