//
// UsageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response containing usage, limits, plan, and billing. */
public struct UsageResponse: Codable, JSONEncodable, Hashable {

    public var usage: Usage?
    public var limits: Limits?
    public var plan: Plan?
    public var billing: Billing?

    public init(usage: Usage? = nil, limits: Limits? = nil, plan: Plan? = nil, billing: Billing? = nil) {
        self.usage = usage
        self.limits = limits
        self.plan = plan
        self.billing = billing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case usage
        case limits
        case plan
        case billing
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(usage, forKey: .usage)
        try container.encodeIfPresent(limits, forKey: .limits)
        try container.encodeIfPresent(plan, forKey: .plan)
        try container.encodeIfPresent(billing, forKey: .billing)
    }
}

