//
// UsersListOAuthProviders200ResponseProvidersInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsersListOAuthProviders200ResponseProvidersInner: Codable, JSONEncodable, Hashable {

    public var provider: String?
    public var providerId: String?
    public var email: String?
    public var linkedAt: Date?

    public init(provider: String? = nil, providerId: String? = nil, email: String? = nil, linkedAt: Date? = nil) {
        self.provider = provider
        self.providerId = providerId
        self.email = email
        self.linkedAt = linkedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case providerId
        case email
        case linkedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(providerId, forKey: .providerId)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(linkedAt, forKey: .linkedAt)
    }
}

