//
// UsersLinkOAuthProvider200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsersLinkOAuthProvider200Response: Codable, JSONEncodable, Hashable {

    public var redirectUrl: String?

    public init(redirectUrl: String? = nil) {
        self.redirectUrl = redirectUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case redirectUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(redirectUrl, forKey: .redirectUrl)
    }
}

