//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct User: Codable, JSONEncodable, Hashable {

    public enum Role: String, Codable, CaseIterable {
        case owner = "owner"
        case admin = "admin"
        case member = "member"
        case viewer = "viewer"
    }
    public var id: String?
    public var email: String?
    public var firstName: String?
    public var lastName: String?
    public var fullName: String?
    public var avatar: String?
    public var role: Role?
    /** Application-level role slug from the project's Multi-Role feature (e.g. \"customer\", \"seller\"). Null for org-level (org/admin/member/viewer) users who aren't project end-users. */
    public var customRole: String?
    /** True for a guest session created via POST /api/auth/anonymous that hasn't been converted to a full account yet. */
    public var isAnonymous: Bool?
    public var emailVerified: Bool?
    public var phoneVerified: Bool?
    public var twoFactorEnabled: Bool?
    public var lastLogin: Date?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var org: OrganizationSummary?

    public init(id: String? = nil, email: String? = nil, firstName: String? = nil, lastName: String? = nil, fullName: String? = nil, avatar: String? = nil, role: Role? = nil, customRole: String? = nil, isAnonymous: Bool? = nil, emailVerified: Bool? = nil, phoneVerified: Bool? = nil, twoFactorEnabled: Bool? = nil, lastLogin: Date? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, org: OrganizationSummary? = nil) {
        self.id = id
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
        self.fullName = fullName
        self.avatar = avatar
        self.role = role
        self.customRole = customRole
        self.isAnonymous = isAnonymous
        self.emailVerified = emailVerified
        self.phoneVerified = phoneVerified
        self.twoFactorEnabled = twoFactorEnabled
        self.lastLogin = lastLogin
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.org = org
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case email
        case firstName
        case lastName
        case fullName
        case avatar
        case role
        case customRole
        case isAnonymous
        case emailVerified
        case phoneVerified
        case twoFactorEnabled
        case lastLogin
        case createdAt
        case updatedAt
        case org
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(fullName, forKey: .fullName)
        try container.encodeIfPresent(avatar, forKey: .avatar)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(customRole, forKey: .customRole)
        try container.encodeIfPresent(isAnonymous, forKey: .isAnonymous)
        try container.encodeIfPresent(emailVerified, forKey: .emailVerified)
        try container.encodeIfPresent(phoneVerified, forKey: .phoneVerified)
        try container.encodeIfPresent(twoFactorEnabled, forKey: .twoFactorEnabled)
        try container.encodeIfPresent(lastLogin, forKey: .lastLogin)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(org, forKey: .org)
    }
}

