//
// WalletTransaction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Wallet transaction record (txHash, address, chain, from, to, amount, status, confirmations, etc.). */
public struct WalletTransaction: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case pending = "pending"
        case completed = "completed"
        case failed = "failed"
    }
    public enum MainTxStatus: String, Codable, CaseIterable {
        case pending = "pending"
        case confirmed = "confirmed"
        case failed = "failed"
    }
    public var id: String?
    public var txHash: String?
    public var mainTxHash: String?
    public var address: String?
    public var chain: String?
    public var from: String?
    public var to: String?
    public var fromAddress: String?
    public var toAddress: String?
    /** Transaction amount (string to handle large numbers) */
    public var amount: String?
    public var currency: String?
    public var type: String?
    public var status: Status?
    public var mainTxStatus: MainTxStatus?
    public var confirmations: Int?
    public var blockNumber: Int?
    public var blockHash: String?
    /** Network fee (string to handle large numbers) */
    public var networkFee: String?
    public var mainTxConfirmedAt: Date?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: String? = nil, txHash: String? = nil, mainTxHash: String? = nil, address: String? = nil, chain: String? = nil, from: String? = nil, to: String? = nil, fromAddress: String? = nil, toAddress: String? = nil, amount: String? = nil, currency: String? = nil, type: String? = nil, status: Status? = nil, mainTxStatus: MainTxStatus? = nil, confirmations: Int? = nil, blockNumber: Int? = nil, blockHash: String? = nil, networkFee: String? = nil, mainTxConfirmedAt: Date? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.txHash = txHash
        self.mainTxHash = mainTxHash
        self.address = address
        self.chain = chain
        self.from = from
        self.to = to
        self.fromAddress = fromAddress
        self.toAddress = toAddress
        self.amount = amount
        self.currency = currency
        self.type = type
        self.status = status
        self.mainTxStatus = mainTxStatus
        self.confirmations = confirmations
        self.blockNumber = blockNumber
        self.blockHash = blockHash
        self.networkFee = networkFee
        self.mainTxConfirmedAt = mainTxConfirmedAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case txHash
        case mainTxHash
        case address
        case chain
        case from
        case to
        case fromAddress
        case toAddress
        case amount
        case currency
        case type
        case status
        case mainTxStatus
        case confirmations
        case blockNumber
        case blockHash
        case networkFee
        case mainTxConfirmedAt
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(txHash, forKey: .txHash)
        try container.encodeIfPresent(mainTxHash, forKey: .mainTxHash)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(chain, forKey: .chain)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(to, forKey: .to)
        try container.encodeIfPresent(fromAddress, forKey: .fromAddress)
        try container.encodeIfPresent(toAddress, forKey: .toAddress)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(mainTxStatus, forKey: .mainTxStatus)
        try container.encodeIfPresent(confirmations, forKey: .confirmations)
        try container.encodeIfPresent(blockNumber, forKey: .blockNumber)
        try container.encodeIfPresent(blockHash, forKey: .blockHash)
        try container.encodeIfPresent(networkFee, forKey: .networkFee)
        try container.encodeIfPresent(mainTxConfirmedAt, forKey: .mainTxConfirmedAt)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

