//
// WalletBalance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Wallet balance (address, chain, confirmed, unconfirmed, total, currency, lastUpdated). */
public struct WalletBalance: Codable, JSONEncodable, Hashable {

    public var address: String?
    public var chain: String?
    /** Confirmed balance (string to handle large numbers) */
    public var confirmed: String?
    /** Unconfirmed balance (string to handle large numbers) */
    public var unconfirmed: String?
    /** Total balance (string to handle large numbers) */
    public var total: String?
    public var currency: String?
    public var lastUpdated: Date?

    public init(address: String? = nil, chain: String? = nil, confirmed: String? = nil, unconfirmed: String? = nil, total: String? = nil, currency: String? = nil, lastUpdated: Date? = nil) {
        self.address = address
        self.chain = chain
        self.confirmed = confirmed
        self.unconfirmed = unconfirmed
        self.total = total
        self.currency = currency
        self.lastUpdated = lastUpdated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case chain
        case confirmed
        case unconfirmed
        case total
        case currency
        case lastUpdated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(chain, forKey: .chain)
        try container.encodeIfPresent(confirmed, forKey: .confirmed)
        try container.encodeIfPresent(unconfirmed, forKey: .unconfirmed)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(lastUpdated, forKey: .lastUpdated)
    }
}

