//
// WalletCreateWebhookRequestFilters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WalletCreateWebhookRequestFilters: Codable, JSONEncodable, Hashable {

    public enum Chains: String, Codable, CaseIterable {
        case ethereum = "ethereum"
        case binance = "binance"
        case bsc = "bsc"
        case polygon = "polygon"
        case arbitrum = "arbitrum"
        case optimism = "optimism"
        case base = "base"
        case avalanche = "avalanche"
        case celo = "celo"
        case bitcoin = "bitcoin"
        case litecoin = "litecoin"
        case dogecoin = "dogecoin"
        case solana = "solana"
        case tron = "tron"
        case ripple = "ripple"
        case cardano = "cardano"
        case ton = "ton"
    }
    /** Filter by address IDs (optional) */
    public var addresses: [String]?
    /** Filter by chains (optional) */
    public var chains: [Chains]?

    public init(addresses: [String]? = nil, chains: [Chains]? = nil) {
        self.addresses = addresses
        self.chains = chains
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addresses
        case chains
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(addresses, forKey: .addresses)
        try container.encodeIfPresent(chains, forKey: .chains)
    }
}

