//
// WalletRegisterAddressRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WalletRegisterAddressRequest: Codable, JSONEncodable, Hashable {

    public enum Chain: String, Codable, CaseIterable {
        case ethereum = "ethereum"
        case binance = "binance"
        case bsc = "bsc"
        case polygon = "polygon"
        case arbitrum = "arbitrum"
        case optimism = "optimism"
        case base = "base"
        case avalanche = "avalanche"
        case celo = "celo"
        case bitcoin = "bitcoin"
        case litecoin = "litecoin"
        case dogecoin = "dogecoin"
        case solana = "solana"
        case tron = "tron"
        case ripple = "ripple"
        case cardano = "cardano"
        case ton = "ton"
    }
    /** Public wallet address */
    public var address: String
    /** Blockchain network (EVM, UTXO, or chain-specific). Use bsc or binance for BNB Smart Chain; avalanche for Avalanche C-Chain. */
    public var chain: Chain
    /** HD wallet derivation path (metadata only) */
    public var derivationPath: String?
    /** Optional label for the address */
    public var label: String?
    /** Optional project ID */
    public var projectId: String?

    public init(address: String, chain: Chain, derivationPath: String? = nil, label: String? = nil, projectId: String? = nil) {
        self.address = address
        self.chain = chain
        self.derivationPath = derivationPath
        self.label = label
        self.projectId = projectId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case chain
        case derivationPath
        case label
        case projectId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(chain, forKey: .chain)
        try container.encodeIfPresent(derivationPath, forKey: .derivationPath)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(projectId, forKey: .projectId)
    }
}

