//
// WebhookLogResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Last HTTP response from your server (if any) */
public struct WebhookLogResponse: Codable, JSONEncodable, Hashable {

    /** HTTP status code from your endpoint */
    public var status: Int?
    /** Parsed JSON when possible; otherwise structure varies */
    public var body: AnyCodable?
    public var headers: AnyCodable?

    public init(status: Int? = nil, body: AnyCodable? = nil, headers: AnyCodable? = nil) {
        self.status = status
        self.body = body
        self.headers = headers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case body
        case headers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encodeIfPresent(headers, forKey: .headers)
    }
}

