//
// WebPushSubscriptionKeys.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WebPushSubscriptionKeys: Codable, JSONEncodable, Hashable {

    /** The subscription's P-256 ECDH public key (base64url). */
    public var p256dh: String
    /** The subscription's auth secret (base64url). */
    public var auth: String

    public init(p256dh: String, auth: String) {
        self.p256dh = p256dh
        self.auth = auth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case p256dh
        case auth
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(p256dh, forKey: .p256dh)
        try container.encode(auth, forKey: .auth)
    }
}

