//
// WebPushUnsubscribeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WebPushUnsubscribeRequest: Codable, JSONEncodable, Hashable {

    /** The push-service endpoint of the subscription to remove. */
    public var endpoint: String

    public init(endpoint: String) {
        self.endpoint = endpoint
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpoint
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(endpoint, forKey: .endpoint)
    }
}

