//
// WebPushConfigResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WebPushConfigResponseData: Codable, JSONEncodable, Hashable {

    /** Whether native Web Push is enabled for this project. */
    public var enabled: Bool?
    /** Whether a VAPID keypair has been provisioned. */
    public var hasKeys: Bool?
    /** The VAPID application-server public key clients subscribe with. Null when native Web Push is not enabled.  */
    public var publicKey: String?
    /** RFC 8292 contact subject (a `mailto:` address or `https` URL). */
    public var vapidSubject: String?
    /** When the current VAPID keypair was generated. */
    public var generatedAt: Date?

    public init(enabled: Bool? = nil, hasKeys: Bool? = nil, publicKey: String? = nil, vapidSubject: String? = nil, generatedAt: Date? = nil) {
        self.enabled = enabled
        self.hasKeys = hasKeys
        self.publicKey = publicKey
        self.vapidSubject = vapidSubject
        self.generatedAt = generatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case hasKeys
        case publicKey
        case vapidSubject
        case generatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(hasKeys, forKey: .hasKeys)
        try container.encodeIfPresent(publicKey, forKey: .publicKey)
        try container.encodeIfPresent(vapidSubject, forKey: .vapidSubject)
        try container.encodeIfPresent(generatedAt, forKey: .generatedAt)
    }
}

